<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;

/**
 * @class DevelopmentController
 * @brief Controlador para utilidades de desarrollo
 *
 * Clase que gestiona las utilidades dispuestas para los desarrolladores y administradores avanzados
 *
 * @author Ing. Roldan Vargas <rvargas@cenditel.gob.ve> | <roldandvg@gmail.com>
 * @license <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>
 *              LICENCIA DE SOFTWARE CENDITEL
 *          </a>
 */
class DevelopmentController extends Controller
{
    /**
     * Muestra un elemento
     *
     * @author Ing. Roldan Vargas <rvargas@cenditel.gob.ve> | <roldandvg@gmail.com>
     * @return \Illuminate\Contracts\View\View Vista solicitada
     */
    public function getElement($el)
    {
        /** @var array Vista a retornar */
        $view = [
            'icons' => [
                'view' => 'pack-icons',
                'vars' => []
            ],
            'components' => [
                'view' => 'ui-elements',
                'vars' => []
            ],
        ];


        if ($el === "icons") {
            /** @var array Arreglo de classes del paquete de íconos ICOFONTS */
            $icofonts = [
                'General' => [
                    'icofont-angry-monster', 'icofont-bathtub', 'icofont-bird-wings', 'icofont-bow',
                    'icofont-brain-alt', 'icofont-butterfly-alt', 'icofont-castle', 'icofont-circuit',
                    'icofont-dart', 'icofont-dice-alt', 'icofont-disability-race', 'icofont-diving-goggle',
                    'icofont-fire-alt', 'icofont-flame-torch', 'icofont-flora-flower', 'icofont-flora',
                    'icofont-gift-box', 'icofont-halloween-pumpkin', 'icofont-hand-power', 'icofont-hand-thunder',
                    'icofont-king-crown', 'icofont-king-monster', 'icofont-love', 'icofont-magician-hat',
                    'icofont-native-american', 'icofont-open-eye', 'icofont-owl-look', 'icofont-phoenix',
                    'icofont-queen-crown', 'icofont-robot-face', 'icofont-sand-clock', 'icofont-shield-alt',
                    'icofont-ship-wheel', 'icofont-skull-danger', 'icofont-skull-face', 'icofont-snail',
                    'icofont-snow-alt', 'icofont-snow-flake', 'icofont-snowmobile', 'icofont-space-shuttle',
                    'icofont-star-shape', 'icofont-swirl', 'icofont-tattoo-wing', 'icofont-throne', 'icofont-touch',
                    'icofont-tree-alt', 'icofont-triangle', 'icofont-unity-hand', 'icofont-weed', 'icofont-woman-bird',
                    'icofont-bank-alt', 'icofont-barcode', 'icofont-basket', 'icofont-bill-alt', 'icofont-billboard',
                    'icofont-briefcase-alt-1', 'icofont-briefcase-alt-2', 'icofont-building-alt',
                    'icofont-businessman', 'icofont-businesswoman', 'icofont-cart-alt', 'icofont-chair',
                    'icofont-clip', 'icofont-coins', 'icofont-company', 'icofont-contact-add', 'icofont-deal',
                    'icofont-files', 'icofont-growth', 'icofont-id-card', 'icofont-idea', 'icofont-list',
                    'icofont-meeting-add', 'icofont-money-bag', 'icofont-people', 'icofont-pie-chart',
                    'icofont-presentation-alt', 'icofont-stamp', 'icofont-stock-mobile', 'icofont-support',
                    'icofont-tasks-alt', 'icofont-wheel', 'icofont-chart-arrows-axis', 'icofont-chart-bar-graph',
                    'icofont-chart-flow-alt-1', 'icofont-chart-flow-alt-2', 'icofont-chart-flow',
                    'icofont-chart-histogram-alt', 'icofont-chart-histogram', 'icofont-chart-line-alt',
                    'icofont-chart-line', 'icofont-chart-pie-alt', 'icofont-chart-pie', 'icofont-chart-radar-graph',
                ],
                'Animales' => [
                    'icofont-animal-bat', 'icofont-animal-bear-tracks', 'icofont-animal-bear',
                    'icofont-animal-bird-alt', 'icofont-animal-bird', 'icofont-animal-bone', 'icofont-animal-bull',
                    'icofont-animal-camel-alt', 'icofont-animal-camel-head', 'icofont-animal-camel',
                    'icofont-animal-cat-alt-1', 'icofont-animal-cat-alt-2', 'icofont-animal-cat-alt-3',
                    'icofont-animal-cat-alt-4', 'icofont-animal-cat-with-dog', 'icofont-animal-cat',
                    'icofont-animal-cow-head', 'icofont-animal-cow', 'icofont-animal-crab', 'icofont-animal-crocodile',
                    'icofont-animal-deer-head', 'icofont-animal-dog-alt', 'icofont-animal-dog-barking',
                    'icofont-animal-dog', 'icofont-animal-dolphin', 'icofont-animal-duck-tracks',
                    'icofont-animal-eagle-head', 'icofont-animal-eaten-fish', 'icofont-animal-elephant-alt',
                    'icofont-animal-elephant-head-alt', 'icofont-animal-elephant-head', 'icofont-animal-elephant',
                    'icofont-animal-elk', 'icofont-animal-fish-alt-1', 'icofont-animal-fish-alt-2',
                    'icofont-animal-fish-alt-3', 'icofont-animal-fish-alt-4', 'icofont-animal-fish',
                    'icofont-animal-fox-alt', 'icofont-animal-fox', 'icofont-animal-frog-tracks',
                    'icofont-animal-frog', 'icofont-animal-froggy', 'icofont-animal-giraffe-alt',
                    'icofont-animal-giraffe', 'icofont-animal-goat-head-alt-1', 'icofont-animal-goat-head-alt-2',
                    'icofont-animal-goat-head', 'icofont-animal-gorilla', 'icofont-animal-hen-tracks',
                    'icofont-animal-horse-head-alt-1', 'icofont-animal-horse-head-alt-2',
                    'icofont-animal-horse-head', 'icofont-animal-horse-tracks', 'icofont-animal-jellyfish',
                    'icofont-animal-kangaroo', 'icofont-animal-lemur', 'icofont-animal-lion-alt',
                    'icofont-animal-lion-head-alt', 'icofont-animal-lion-head', 'icofont-animal-lion',
                    'icofont-animal-monkey-alt-1', 'icofont-animal-monkey-alt-2', 'icofont-animal-monkey-alt-3',
                    'icofont-animal-monkey', 'icofont-animal-octopus-alt', 'icofont-animal-octopus',
                    'icofont-animal-owl', 'icofont-animal-panda-alt', 'icofont-animal-panda', 'icofont-animal-panther',
                    'icofont-animal-parrot-lip', 'icofont-animal-parrot', 'icofont-animal-paw',
                    'icofont-animal-pelican', 'icofont-animal-penguin', 'icofont-animal-pig-alt',
                    'icofont-animal-pig', 'icofont-animal-pigeon-alt', 'icofont-animal-pigeon',
                    'icofont-animal-pigeons', 'icofont-animal-rabbit-running', 'icofont-animal-rat-alt',
                    'icofont-animal-rhino-head', 'icofont-animal-rhino', 'icofont-animal-rooster',
                    'icofont-animal-seahorse', 'icofont-animal-seal', 'icofont-animal-shrimp',
                    'icofont-animal-snail-alt-1', 'icofont-animal-snail-alt-2', 'icofont-animal-snail',
                    'icofont-animal-snake', 'icofont-animal-squid', 'icofont-animal-squirrel',
                    'icofont-animal-tiger-alt', 'icofont-animal-tiger', 'icofont-animal-turtle',
                    'icofont-animal-whale', 'icofont-animal-woodpecker', 'icofont-animal-zebra',
                ],
                'Marcas' => [
                    'icofont-brand-acer', 'icofont-brand-adidas', 'icofont-brand-adobe',
                    'icofont-brand-air-new-zealand', 'icofont-brand-airbnb', 'icofont-brand-aircell',
                    'icofont-brand-airtel', 'icofont-brand-alcatel', 'icofont-brand-alibaba',
                    'icofont-brand-aliexpress', 'icofont-brand-alipay', 'icofont-brand-amazon', 'icofont-amazon-alt',
                    'icofont-amazon', 'icofont-brand-xiaomi',
                    'icofont-brand-amd', 'icofont-brand-american-airlines', 'icofont-brand-android-robot',
                    'icofont-brand-android', 'icofont-brand-aol', 'icofont-brand-apple', 'icofont-brand-appstore',
                    'icofont-brand-asus', 'icofont-brand-ati', 'icofont-brand-att', 'icofont-brand-audi',
                    'icofont-brand-axiata', 'icofont-brand-bada', 'icofont-brand-bbc', 'icofont-brand-bing',
                    'icofont-brand-blackberry', 'icofont-brand-bmw', 'icofont-brand-box', 'icofont-brand-burger-king',
                    'icofont-brand-business-insider', 'icofont-brand-buzzfeed', 'icofont-brand-cannon',
                    'icofont-brand-casio', 'icofont-brand-china-mobile', 'icofont-brand-china-telecom',
                    'icofont-brand-china-unicom', 'icofont-brand-cisco', 'icofont-brand-citibank',
                    'icofont-brand-cnet', 'icofont-brand-cnn', 'icofont-brand-cocal-cola', 'icofont-brand-compaq',
                    'icofont-brand-copy', 'icofont-brand-debian', 'icofont-brand-delicious', 'icofont-brand-dell',
                    'icofont-brand-designbump', 'icofont-brand-designfloat', 'icofont-brand-disney',
                    'icofont-brand-dodge', 'icofont-brand-dove', 'icofont-brand-ebay', 'icofont-brand-eleven',
                    'icofont-brand-emirates', 'icofont-brand-espn', 'icofont-brand-etihad-airways',
                    'icofont-brand-etisalat', 'icofont-brand-etsy', 'icofont-brand-facebook', 'icofont-brand-fastrack',
                    'icofont-brand-fedex', 'icofont-brand-ferrari', 'icofont-brand-fitbit', 'icofont-brand-flikr',
                    'icofont-brand-forbes', 'icofont-brand-foursquare', 'icofont-brand-fox', 'icofont-brand-foxconn',
                    'icofont-brand-fujitsu', 'icofont-brand-general-electric', 'icofont-brand-gillette',
                    'icofont-brand-gizmodo', 'icofont-brand-gnome', 'icofont-brand-google', 'icofont-brand-gopro',
                    'icofont-brand-gucci', 'icofont-brand-hallmark', 'icofont-brand-hi5', 'icofont-brand-honda',
                    'icofont-brand-hp', 'icofont-brand-hsbc', 'icofont-brand-htc', 'icofont-brand-huawei',
                    'icofont-brand-hulu', 'icofont-brand-hyundai', 'icofont-brand-ibm', 'icofont-brand-icofont',
                    'icofont-brand-icq', 'icofont-brand-ikea', 'icofont-brand-imdb', 'icofont-brand-indiegogo',
                    'icofont-brand-intel', 'icofont-brand-ipair', 'icofont-brand-jaguar', 'icofont-brand-java',
                    'icofont-brand-joomshaper', 'icofont-brand-kickstarter', 'icofont-brand-kik',
                    'icofont-brand-lastfm', 'icofont-brand-lego', 'icofont-brand-lenovo', 'icofont-brand-levis',
                    'icofont-brand-lexus', 'icofont-brand-lg', 'icofont-brand-life-hacker',
                    'icofont-brand-line-messenger', 'icofont-brand-linkedin', 'icofont-brand-linux-mint',
                    'icofont-brand-linux', 'icofont-brand-lionix', 'icofont-brand-live-messenger',
                    'icofont-brand-loreal', 'icofont-brand-louis-vuitton', 'icofont-brand-mac-os',
                    'icofont-brand-marvel-app', 'icofont-brand-mashable', 'icofont-brand-mazda',
                    'icofont-brand-mcdonals', 'icofont-brand-mercedes', 'icofont-brand-micromax',
                    'icofont-brand-microsoft', 'icofont-brand-mobileme', 'icofont-brand-mobily',
                    'icofont-brand-motorola', 'icofont-brand-msi', 'icofont-brand-mts', 'icofont-brand-myspace',
                    'icofont-brand-mytv', 'icofont-brand-nasa', 'icofont-brand-natgeo', 'icofont-brand-nbc',
                    'icofont-brand-nescafe', 'icofont-brand-nestle', 'icofont-brand-netflix', 'icofont-brand-nexus',
                    'icofont-brand-nike', 'icofont-brand-nokia', 'icofont-brand-nvidia', 'icofont-brand-omega',
                    'icofont-brand-opensuse', 'icofont-brand-oracle', 'icofont-brand-panasonic',
                    'icofont-brand-paypal', 'icofont-brand-pepsi', 'icofont-brand-philips', 'icofont-brand-pizza-hut',
                    'icofont-brand-playstation', 'icofont-brand-puma', 'icofont-brand-qatar-air', 'icofont-brand-qvc',
                    'icofont-brand-readernaut', 'icofont-brand-redbull', 'icofont-brand-reebok',
                    'icofont-brand-reuters', 'icofont-brand-samsung', 'icofont-brand-sap',
                    'icofont-brand-saudia-airlines', 'icofont-brand-scribd', 'icofont-brand-shell',
                    'icofont-brand-siemens', 'icofont-brand-sk-telecom', 'icofont-brand-slideshare',
                    'icofont-brand-smashing-magazine', 'icofont-brand-snapchat', 'icofont-brand-sony-ericsson',
                    'icofont-brand-sony', 'icofont-brand-soundcloud', 'icofont-brand-sprint', 'icofont-brand-squidoo',
                    'icofont-brand-starbucks', 'icofont-brand-stc', 'icofont-brand-steam', 'icofont-brand-suzuki',
                    'icofont-brand-symbian', 'icofont-brand-t-mobile', 'icofont-brand-tango', 'icofont-brand-target',
                    'icofont-brand-tata-indicom', 'icofont-brand-techcrunch', 'icofont-brand-telenor',
                    'icofont-brand-teliasonera', 'icofont-brand-tesla', 'icofont-brand-the-verge',
                    'icofont-brand-thenextweb', 'icofont-brand-toshiba', 'icofont-brand-toyota',
                    'icofont-brand-tribenet', 'icofont-brand-ubuntu', 'icofont-brand-unilever', 'icofont-brand-vaio',
                    'icofont-brand-verizon', 'icofont-brand-viber', 'icofont-brand-vodafone',
                    'icofont-brand-volkswagen', 'icofont-brand-walmart', 'icofont-brand-warnerbros',
                    'icofont-brand-whatsapp', 'icofont-brand-wikipedia', 'icofont-brand-windows',
                    'icofont-brand-wire', 'icofont-brand-yahoobuzz', 'icofont-brand-yamaha', 'icofont-brand-youtube',
                    'icofont-brand-zain', 'icofont-brand-joomla', 'icofont-brand-drupal', 'icofont-brand-wordpress',
                ],
                'Monedas' => [
                    'icofont-cur-afghani-false', 'icofont-cur-afghani-minus',
                    'icofont-cur-afghani-plus', 'icofont-cur-afghani-true', 'icofont-cur-afghani',
                    'icofont-cur-baht-false', 'icofont-cur-baht-minus', 'icofont-cur-baht-plus',
                    'icofont-cur-baht-true', 'icofont-cur-baht', 'icofont-cur-bitcoin-false',
                    'icofont-cur-bitcoin-minus', 'icofont-cur-bitcoin-plus', 'icofont-cur-bitcoin-true',
                    'icofont-cur-bitcoin', 'icofont-cur-dollar-flase', 'icofont-cur-dollar-minus',
                    'icofont-cur-dollar-plus', 'icofont-cur-dollar-true', 'icofont-cur-dollar',
                    'icofont-cur-dong-false', 'icofont-cur-dong-minus', 'icofont-cur-dong-plus',
                    'icofont-cur-dong-true', 'icofont-cur-dong', 'icofont-cur-euro-false', 'icofont-cur-euro-minus',
                    'icofont-cur-euro-plus', 'icofont-cur-euro-true', 'icofont-cur-euro', 'icofont-cur-frank-false',
                    'icofont-cur-frank-minus', 'icofont-cur-frank-plus', 'icofont-cur-frank-true', 'icofont-cur-frank',
                    'icofont-cur-hryvnia-false', 'icofont-cur-hryvnia-minus', 'icofont-cur-hryvnia-plus',
                    'icofont-cur-hryvnia-true', 'icofont-cur-hryvnia', 'icofont-cur-lira-false',
                    'icofont-cur-lira-minus', 'icofont-cur-lira-plus', 'icofont-cur-lira-true', 'icofont-cur-lira',
                    'icofont-cur-peseta-false', 'icofont-cur-peseta-minus', 'icofont-cur-peseta-plus',
                    'icofont-cur-peseta-true', 'icofont-cur-peseta', 'icofont-cur-peso-false',
                    'icofont-cur-peso-minus', 'icofont-cur-peso-plus', 'icofont-cur-peso-true', 'icofont-cur-peso',
                    'icofont-cur-pound-false', 'icofont-cur-pound-minus', 'icofont-cur-pound-plus',
                    'icofont-cur-pound-true', 'icofont-cur-pound', 'icofont-cur-renminbi-false',
                    'icofont-cur-renminbi-minus', 'icofont-cur-renminbi-plus', 'icofont-cur-renminbi-true',
                    'icofont-cur-renminbi', 'icofont-cur-riyal-false', 'icofont-cur-riyal-minus',
                    'icofont-cur-riyal-plus', 'icofont-cur-riyal-true', 'icofont-cur-riyal', 'icofont-cur-rouble-false',
                    'icofont-cur-rouble-minus', 'icofont-cur-rouble-plus', 'icofont-cur-rouble-true',
                    'icofont-cur-rouble', 'icofont-cur-rupee-false', 'icofont-cur-rupee-minus',
                    'icofont-cur-rupee-plus',
                    'icofont-cur-rupee-true', 'icofont-cur-rupee', 'icofont-cur-taka-false', 'icofont-cur-taka-minus',
                    'icofont-cur-taka-plus', 'icofont-cur-taka-true', 'icofont-cur-taka',
                    'icofont-cur-turkish-lira-false', 'icofont-cur-turkish-lira-minus', 'icofont-cur-turkish-lira-plus',
                    'icofont-cur-turkish-lira-true', 'icofont-cur-turkish-lira', 'icofont-cur-won-false',
                    'icofont-cur-won-minus', 'icofont-cur-won-plus', 'icofont-cur-won-true', 'icofont-cur-won',
                    'icofont-cur-yen-false', 'icofont-cur-yen-minus', 'icofont-cur-yen-plus', 'icofont-cur-yen-true',
                    'icofont-cur-yen',
                ],
                'Archivos y Carpetas' => [
                    'icofont-file-audio', 'icofont-file-avi-mp4', 'icofont-file-bmp', 'icofont-file-code',
                    'icofont-file-css', 'icofont-file-document', 'icofont-file-eps', 'icofont-file-excel',
                    'icofont-file-exe', 'icofont-file-file', 'icofont-file-flv', 'icofont-file-gif',
                    'icofont-file-html5', 'icofont-file-image', 'icofont-file-iso', 'icofont-file-java',
                    'icofont-file-javascript', 'icofont-file-jpg', 'icofont-file-midi', 'icofont-file-mov',
                    'icofont-file-mp3', 'icofont-file-pdf', 'icofont-file-php', 'icofont-file-png',
                    'icofont-file-powerpoint', 'icofont-file-presentation', 'icofont-file-psb', 'icofont-file-psd',
                    'icofont-file-python', 'icofont-file-ruby', 'icofont-file-spreadsheet', 'icofont-file-sql',
                    'icofont-file-svg', 'icofont-file-text', 'icofont-file-tiff', 'icofont-file-video',
                    'icofont-file-wave', 'icofont-file-wmv', 'icofont-file-word', 'icofont-file-zip'
                ],
                "Emoticones" => [
                    'icofont-emo-angry', 'icofont-emo-astonished', 'icofont-emo-confounded', 'icofont-emo-confused',
                    'icofont-emo-crying', 'icofont-emo-dizzy', 'icofont-emo-expressionless', 'icofont-emo-heart-eyes',
                    'icofont-emo-laughing', 'icofont-emo-nerd-smile', 'icofont-emo-open-mouth', 'icofont-emo-rage',
                    'icofont-emo-rolling-eyes', 'icofont-emo-sad', 'icofont-emo-simple-smile',
                    'icofont-emo-slightly-smile', 'icofont-emo-smirk', 'icofont-emo-stuck-out-tongue',
                    'icofont-emo-wink-smile', 'icofont-emo-worried'
                ],
                "Interfaz de Usuario" => [
                    'icofont-ui-add',
                    'icofont-ui-alarm', 'icofont-ui-battery', 'icofont-ui-block', 'icofont-ui-bluetooth',
                    'icofont-ui-brightness', 'icofont-ui-browser', 'icofont-ui-calculator', 'icofont-ui-calendar',
                    'icofont-ui-call', 'icofont-ui-camera', 'icofont-ui-cart', 'icofont-ui-cell-phone',
                    'icofont-ui-chat', 'icofont-ui-check', 'icofont-ui-clip-board', 'icofont-ui-clip',
                    'icofont-ui-clock', 'icofont-ui-close', 'icofont-ui-contact-list', 'icofont-ui-copy',
                    'icofont-ui-cut', 'icofont-ui-delete', 'icofont-ui-dial-phone', 'icofont-ui-edit',
                    'icofont-ui-email', 'icofont-ui-file', 'icofont-ui-fire-wall', 'icofont-ui-flash-light',
                    'icofont-ui-flight', 'icofont-ui-folder', 'icofont-ui-game', 'icofont-ui-handicapped',
                    'icofont-ui-head-phone', 'icofont-ui-home', 'icofont-ui-image', 'icofont-ui-keyboard',
                    'icofont-ui-laoding', 'icofont-ui-lock', 'icofont-ui-love-add', 'icofont-ui-love-broken',
                    'icofont-ui-love-remove', 'icofont-ui-love', 'icofont-ui-map', 'icofont-ui-message',
                    'icofont-ui-messaging', 'icofont-ui-movie', 'icofont-ui-music-player', 'icofont-ui-music',
                    'icofont-ui-mute', 'icofont-ui-network', 'icofont-ui-next', 'icofont-ui-note', 'icofont-ui-office',
                    'icofont-ui-password', 'icofont-ui-pause', 'icofont-ui-play-stop', 'icofont-ui-play',
                    'icofont-ui-pointer', 'icofont-ui-power', 'icofont-ui-press', 'icofont-ui-previous',
                    'icofont-ui-rate-add', 'icofont-ui-rate-blank', 'icofont-ui-rate-remove', 'icofont-ui-rating',
                    'icofont-ui-record', 'icofont-ui-remove', 'icofont-ui-reply', 'icofont-ui-rotation',
                    'icofont-ui-rss', 'icofont-ui-search', 'icofont-ui-settings', 'icofont-ui-social-link',
                    'icofont-ui-tag', 'icofont-ui-text-chat', 'icofont-ui-text-loading', 'icofont-ui-theme',
                    'icofont-ui-timer', 'icofont-ui-touch-phone', 'icofont-ui-travel', 'icofont-ui-unlock',
                    'icofont-ui-user-group', 'icofont-ui-user', 'icofont-ui-v-card', 'icofont-ui-video-chat',
                    'icofont-ui-video-message', 'icofont-ui-video-play', 'icofont-ui-video', 'icofont-ui-volume',
                    'icofont-ui-weather', 'icofont-ui-wifi', 'icofont-ui-zoom-in', 'icofont-ui-zoom-out',
                ],
                "Usuarios" => [
                    'icofont-user-alt-1', 'icofont-user-alt-2', 'icofont-user-alt-3', 'icofont-user-alt-4',
                    'icofont-user-alt-5', 'icofont-user-alt-6', 'icofont-user-alt-7', 'icofont-user-female',
                    'icofont-user-male', 'icofont-user-suited', 'icofont-user', 'icofont-users-alt-1',
                    'icofont-users-alt-2', 'icofont-users-alt-3', 'icofont-users-alt-4', 'icofont-users-alt-5',
                    'icofont-users-alt-6', 'icofont-users-social', 'icofont-users', 'icofont-user-search'
                ],
                "Redes Sociales" => [
                    'icofont-social-aim', 'icofont-social-badoo', 'icofont-social-bebo',
                    'icofont-social-behance', 'icofont-social-blogger', 'icofont-social-bootstrap',
                    'icofont-social-brightkite', 'icofont-social-cloudapp', 'icofont-social-concrete5',
                    'icofont-social-designbump', 'icofont-social-designfloat', 'icofont-social-deviantart',
                    'icofont-social-digg', 'icofont-social-dotcms', 'icofont-social-dribble', 'icofont-social-dropbox',
                    'icofont-social-ebuddy', 'icofont-social-ello', 'icofont-social-ember',
                    'icofont-social-envato', 'icofont-social-evernote', 'icofont-social-facebook',
                    'icofont-social-feedburner', 'icofont-social-folkd', 'icofont-social-friendfeed',
                    'icofont-social-ghost', 'icofont-social-github', 'icofont-social-gnome',
                    'icofont-social-google-buzz', 'icofont-social-google-map', 'icofont-social-google-plus',
                    'icofont-social-google-talk', 'icofont-social-hype-machine', 'icofont-social-instagram',
                    'icofont-social-kickstarter', 'icofont-social-line',
                    'icofont-social-linux-mint', 'icofont-social-livejournal', 'icofont-social-magento',
                    'icofont-social-meetup', 'icofont-social-mixx', 'icofont-social-newsvine', 'icofont-social-nimbuss',
                    'icofont-social-opencart', 'icofont-social-oscommerce', 'icofont-social-pandora',
                    'icofont-social-picasa', 'icofont-social-pinterest', 'icofont-social-prestashop',
                    'icofont-social-qik', 'icofont-social-readernaut', 'icofont-social-reddit', 'icofont-social-rss',
                    'icofont-social-shopify', 'icofont-social-silverstripe', 'icofont-social-skype',
                    'icofont-social-slashdot', 'icofont-social-smugmug', 'icofont-social-steam',
                    'icofont-social-stumbleupon', 'icofont-social-technorati', 'icofont-social-telegram',
                    'icofont-social-tinder', 'icofont-social-tumblr', 'icofont-social-twitter', 'icofont-social-typo3',
                    'icofont-social-ubercart', 'icofont-social-viber', 'icofont-social-viddler', 'icofont-social-vimeo',
                    'icofont-social-vine', 'icofont-social-virb', 'icofont-social-virtuemart', 'icofont-social-wechat',
                    'icofont-social-xing', 'icofont-social-yahoo', 'icofont-social-yelp',
                    'icofont-social-zencart', 'icofont-social-500px',
                    'icofont-social-baidu-tieba', 'icofont-social-bbm-messenger', 'icofont-social-delicious',
                    'icofont-social-dribbble', 'icofont-social-facebook-messenger', 'icofont-social-flikr',
                    'icofont-social-foursquare', 'icofont-social-google-hangouts', 'icofont-social-kakaotalk',
                    'icofont-social-kik', 'icofont-social-kiwibox', 'icofont-social-linkedin', 'icofont-social-meetme',
                    'icofont-social-odnoklassniki', 'icofont-social-photobucket', 'icofont-social-qq',
                    'icofont-social-renren', 'icofont-social-slack', 'icofont-social-slidshare',
                    'icofont-social-snapchat', 'icofont-social-soundcloud', 'icofont-social-spotify',
                    'icofont-social-stack-exchange', 'icofont-social-stack-overflow', 'icofont-social-tagged',
                    'icofont-social-trello', 'icofont-social-twitch', 'icofont-social-vk', 'icofont-social-weibo',
                    'icofont-social-whatsapp', 'icofont-social-youku', 'icofont-social-youtube-play',
                    'icofont-social-youtube'
                ],
                "Métodos de Pago" => [
                    'icofont-american-express-alt', 'icofont-american-express',
                    'icofont-apple-pay-alt', 'icofont-apple-pay', 'icofont-bank-transfer-alt', 'icofont-bank-transfer',
                    'icofont-braintree-alt', 'icofont-braintree', 'icofont-cash-on-delivery-alt',
                    'icofont-cash-on-delivery', 'icofont-checkout-alt', 'icofont-checkout', 'icofont-diners-club-alt-1',
                    'icofont-diners-club-alt-2', 'icofont-diners-club-alt-3', 'icofont-diners-club',
                    'icofont-discover-alt', 'icofont-discover', 'icofont-eway-alt', 'icofont-eway',
                    'icofont-google-wallet-alt-1', 'icofont-google-wallet-alt-2', 'icofont-google-wallet-alt-3',
                    'icofont-google-wallet', 'icofont-jcb-alt', 'icofont-jcb', 'icofont-maestro-alt', 'icofont-maestro',
                    'icofont-mastercard-alt', 'icofont-mastercard', 'icofont-payoneer-alt', 'icofont-payoneer',
                    'icofont-paypal-alt', 'icofont-paypal', 'icofont-sage-alt', 'icofont-sage', 'icofont-skrill-alt',
                    'icofont-skrill', 'icofont-stripe-alt', 'icofont-stripe', 'icofont-visa-alt',
                    'icofont-visa-electron', 'icofont-visa', 'icofont-western-union-alt', 'icofont-western-union'
                ],
                'Aplicaciones Web' => [
                    'icofont-android-nexus', 'icofont-android-tablet', 'icofont-apple-watch',
                    'icofont-drwaing-tablet', 'icofont-earphone', 'icofont-flash-drive', 'icofont-game-control',
                    'icofont-headphone-alt', 'icofont-htc-one', 'icofont-imac', 'icofont-ipad-touch', 'icofont-iphone',
                    'icofont-ipod-nano', 'icofont-ipod-touch', 'icofont-keyboard-alt', 'icofont-keyboard-wireless',
                    'icofont-laptop-alt', 'icofont-macbook', 'icofont-magic-mouse', 'icofont-microphone-alt',
                    'icofont-monitor', 'icofont-mouse', 'icofont-nintendo', 'icofont-playstation', 'icofont-psvita',
                    'icofont-radio-mic', 'icofont-refrigerator', 'icofont-samsung-galaxy', 'icofont-surface-tablet',
                    'icofont-washing-machine', 'icofont-wifi-router', 'icofont-wii-u', 'icofont-windows-lumia',
                    'icofont-wireless-mouse', 'icofont-xbox-360', 'icofont-arrow-down', 'icofont-arrow-left',
                    'icofont-arrow-right', 'icofont-arrow-up', 'icofont-block-down', 'icofont-block-left',
                    'icofont-block-right', 'icofont-block-up', 'icofont-bubble-down', 'icofont-bubble-left',
                    'icofont-bubble-right', 'icofont-bubble-up', 'icofont-caret-down', 'icofont-caret-left',
                    'icofont-caret-right', 'icofont-caret-up', 'icofont-circled-down', 'icofont-circled-left',
                    'icofont-circled-right', 'icofont-circled-up', 'icofont-collapse', 'icofont-cursor-drag',
                    'icofont-curved-double-left', 'icofont-curved-double-right', 'icofont-curved-down',
                    'icofont-curved-left', 'icofont-curved-right', 'icofont-curved-up', 'icofont-dotted-down',
                    'icofont-dotted-left', 'icofont-dotted-right', 'icofont-dotted-up', 'icofont-double-left',
                    'icofont-double-right', 'icofont-drag', 'icofont-drag1', 'icofont-drag2', 'icofont-drag3',
                    'icofont-expand-alt', 'icofont-hand-down', 'icofont-hand-drag', 'icofont-hand-drag1',
                    'icofont-hand-drag2', 'icofont-hand-drawn-alt-down', 'icofont-hand-drawn-alt-left',
                    'icofont-hand-drawn-alt-right', 'icofont-hand-drawn-alt-up', 'icofont-hand-drawn-down',
                    'icofont-hand-drawn-left', 'icofont-hand-drawn-right', 'icofont-hand-drawn-up', 'icofont-hand-left',
                    'icofont-hand-right', 'icofont-hand-up', 'icofont-line-block-down', 'icofont-line-block-left',
                    'icofont-line-block-right', 'icofont-line-block-up', 'icofont-long-arrow-down',
                    'icofont-long-arrow-left', 'icofont-long-arrow-right', 'icofont-long-arrow-up',
                    'icofont-rounded-collapse', 'icofont-rounded-double-left', 'icofont-rounded-double-right',
                    'icofont-rounded-down', 'icofont-rounded-expand', 'icofont-rounded-left-down',
                    'icofont-rounded-left-up', 'icofont-rounded-left', 'icofont-rounded-right-down',
                    'icofont-rounded-right-up', 'icofont-rounded-right', 'icofont-rounded-up',
                    'icofont-scroll-bubble-down', 'icofont-scroll-bubble-left', 'icofont-scroll-bubble-right',
                    'icofont-scroll-bubble-up', 'icofont-scroll-double-down', 'icofont-scroll-double-left',
                    'icofont-scroll-double-right', 'icofont-scroll-double-up', 'icofont-scroll-down',
                    'icofont-scroll-left', 'icofont-scroll-long-down', 'icofont-scroll-long-left',
                    'icofont-scroll-long-right', 'icofont-scroll-long-up', 'icofont-scroll-right', 'icofont-scroll-up',
                    'icofont-simple-down', 'icofont-simple-left-down', 'icofont-simple-left-up', 'icofont-simple-left',
                    'icofont-simple-right-down', 'icofont-simple-right-up', 'icofont-simple-right', 'icofont-simple-up',
                    'icofont-square-down', 'icofont-square-left', 'icofont-square-right', 'icofont-square-up',
                    'icofont-stylish-down', 'icofont-stylish-left', 'icofont-stylish-right', 'icofont-stylish-up',
                    'icofont-swoosh-down', 'icofont-swoosh-left', 'icofont-swoosh-right', 'icofont-swoosh-up',
                    'icofont-thin-double-left', 'icofont-thin-double-right', 'icofont-thin-down', 'icofont-thin-left',
                    'icofont-thin-right', 'icofont-thin-up', 'icofont-atom', 'icofont-award', 'icofont-bell-alt',
                    'icofont-book-alt', 'icofont-brainstorming', 'icofont-certificate-alt-1',
                    'icofont-certificate-alt-2', 'icofont-dna-alt-2', 'icofont-education', 'icofont-electron',
                    'icofont-fountain-pen', 'icofont-globe-alt', 'icofont-graduate-alt', 'icofont-group-students',
                    'icofont-hat-alt', 'icofont-hat', 'icofont-instrument', 'icofont-lamp-light',
                    'icofont-microscope-alt', 'icofont-paper', 'icofont-pen-alt-4', 'icofont-pen-nib',
                    'icofont-pencil-alt-5', 'icofont-quill-pen', 'icofont-read-book-alt', 'icofont-read-book',
                    'icofont-school-bag', 'icofont-school-bus', 'icofont-student-alt', 'icofont-student',
                    'icofont-teacher', 'icofont-test-bulb', 'icofont-test-tube-alt', 'icofont-university',
                    'icofont-architecture-alt', 'icofont-architecture',
                    'icofont-barricade', 'icofont-bricks', 'icofont-calculations', 'icofont-cement-mix',
                    'icofont-cement-mixer', 'icofont-danger-zone', 'icofont-drill', 'icofont-eco-energy',
                    'icofont-eco-environmen', 'icofont-energy-air', 'icofont-energy-oil', 'icofont-energy-savings',
                    'icofont-energy-solar', 'icofont-energy-water', 'icofont-engineer', 'icofont-fire-extinguisher-alt',
                    'icofont-fix-tools', 'icofont-glue-oil', 'icofont-hammer-alt', 'icofont-help-robot',
                    'icofont-industries-alt-1', 'icofont-industries-alt-2', 'icofont-industries-alt-3',
                    'icofont-industries-alt-4', 'icofont-industries-alt-5', 'icofont-industries', 'icofont-labour',
                    'icofont-mining', 'icofont-paint-brush', 'icofont-pollution', 'icofont-power-zone',
                    'icofont-radio-active', 'icofont-recycle-alt', 'icofont-recycling-man', 'icofont-safety-hat-light',
                    'icofont-safety-hat', 'icofont-saw', 'icofont-screw-driver', 'icofont-settings-alt',
                    'icofont-tools-alt-1', 'icofont-tools-alt-2', 'icofont-tools-bag', 'icofont-trolley',
                    'icofont-trowel', 'icofont-under-construction-alt', 'icofont-under-construction',
                    'icofont-vehicle-cement', 'icofont-vehicle-crane', 'icofont-vehicle-delivery-van',
                    'icofont-vehicle-dozer', 'icofont-vehicle-excavator', 'icofont-vehicle-trucktor',
                    'icofont-vehicle-wrecking', 'icofont-worker-group', 'icofont-worker', 'icofont-wrench',
                    'icofont-apple',
                    'icofont-arabian-coffee', 'icofont-artichoke', 'icofont-asparagus', 'icofont-avocado',
                    'icofont-baby-food', 'icofont-banana', 'icofont-bbq', 'icofont-beans', 'icofont-beer',
                    'icofont-bell-pepper-capsicum', 'icofont-birthday-cake', 'icofont-bread', 'icofont-broccoli',
                    'icofont-burger', 'icofont-cabbage', 'icofont-carrot', 'icofont-cauli-flower', 'icofont-cheese',
                    'icofont-chef', 'icofont-cherry', 'icofont-chicken-fry', 'icofont-chicken', 'icofont-cocktail',
                    'icofont-coconut', 'icofont-coffee-alt', 'icofont-coffee-mug', 'icofont-coffee-pot', 'icofont-cola',
                    'icofont-corn', 'icofont-croissant', 'icofont-crop-plant', 'icofont-cucumber', 'icofont-cup-cake',
                    'icofont-dining-table', 'icofont-donut', 'icofont-egg-plant', 'icofont-egg-poached',
                    'icofont-farmer', 'icofont-farmer1', 'icofont-fast-food', 'icofont-fish', 'icofont-food-basket',
                    'icofont-food-cart', 'icofont-fork-and-knife', 'icofont-french-fries', 'icofont-fresh-juice',
                    'icofont-fruits', 'icofont-grapes', 'icofont-honey', 'icofont-hot-dog', 'icofont-hotel-alt',
                    'icofont-ice-cream-alt', 'icofont-ice-cream', 'icofont-ketchup', 'icofont-kiwi',
                    'icofont-layered-cake', 'icofont-lemon-alt', 'icofont-lobster', 'icofont-mango', 'icofont-milk',
                    'icofont-mushroom', 'icofont-noodles', 'icofont-onion', 'icofont-orange', 'icofont-pear',
                    'icofont-peas', 'icofont-pepper', 'icofont-pie-alt', 'icofont-pineapple', 'icofont-pizza-slice',
                    'icofont-pizza', 'icofont-plant', 'icofont-popcorn', 'icofont-potato', 'icofont-pumpkin',
                    'icofont-raddish', 'icofont-restaurant-menu', 'icofont-restaurant', 'icofont-salt-and-pepper',
                    'icofont-sandwich', 'icofont-sausage', 'icofont-shrimp', 'icofont-sof-drinks', 'icofont-soup-bowl',
                    'icofont-spoon-and-fork', 'icofont-steak', 'icofont-strawberry', 'icofont-sub-sandwich',
                    'icofont-sushi', 'icofont-taco', 'icofont-tea-pot', 'icofont-tea', 'icofont-tomato',
                    'icofont-waiter-alt', 'icofont-watermelon', 'icofont-wheat', 'icofont-abc', 'icofont-baby-cloth',
                    'icofont-baby-milk-bottle', 'icofont-baby-trolley', 'icofont-back-pack', 'icofont-candy',
                    'icofont-cycling', 'icofont-holding-hands', 'icofont-infant-nipple', 'icofont-kids-scooter',
                    'icofont-safety-pin', 'icofont-teddy-bear', 'icofont-toy-ball', 'icofont-toy-cat',
                    'icofont-toy-duck', 'icofont-toy-elephant', 'icofont-toy-hand', 'icofont-toy-horse',
                    'icofont-toy-lattu', 'icofont-toy-train', 'icofont-unique-idea', 'icofont-bag-alt',
                    'icofont-burglar', 'icofont-cannon-firing', 'icofont-cc-camera', 'icofont-cop-badge', 'icofont-cop',
                    'icofont-court-hammer', 'icofont-court', 'icofont-finger-print', 'icofont-handcuff-alt',
                    'icofont-handcuff', 'icofont-investigation', 'icofont-investigator', 'icofont-jail',
                    'icofont-judge', 'icofont-law-alt-1', 'icofont-law-alt-2', 'icofont-law-alt-3', 'icofont-law-book',
                    'icofont-law-document', 'icofont-law', 'icofont-lawyer-alt-1', 'icofont-lawyer-alt-2',
                    'icofont-lawyer', 'icofont-order', 'icofont-pistol', 'icofont-police-badge', 'icofont-police-cap',
                    'icofont-police-car-alt-1', 'icofont-police-car-alt-2', 'icofont-police-hat', 'icofont-police-van',
                    'icofont-police', 'icofont-protect', 'icofont-scales', 'icofont-thief-alt', 'icofont-thief',
                    'icofont-abacus-alt', 'icofont-abacus', 'icofont-angle', 'icofont-calculator-alt-1',
                    'icofont-calculator-alt-2', 'icofont-circle-ruler-alt', 'icofont-circle-ruler',
                    'icofont-compass-alt-1', 'icofont-compass-alt-2', 'icofont-compass-alt-3', 'icofont-compass-alt-4',
                    'icofont-degrees-alt-1', 'icofont-degrees-alt-2', 'icofont-degrees', 'icofont-golden-ratio',
                    'icofont-marker-alt-1', 'icofont-marker-alt-2', 'icofont-marker-alt-3',
                    'icofont-mathematical-alt-1', 'icofont-mathematical-alt-2', 'icofont-mathematical',
                    'icofont-pen-alt-1', 'icofont-pen-alt-2', 'icofont-pen-alt-3', 'icofont-pen-holder-alt-1',
                    'icofont-pen-holder', 'icofont-pencil-alt-1',
                    'icofont-pencil-alt-2', 'icofont-pencil-alt-3', 'icofont-pencil-alt-4', 'icofont-ruler-alt-1',
                    'icofont-ruler-alt-2', 'icofont-ruler-compass-alt', 'icofont-ruler-compass',
                    'icofont-ruler-pencil-alt-1', 'icofont-ruler-pencil-alt-2', 'icofont-ruler-pencil', 'icofont-ruler',
                    'icofont-rulers-alt', 'icofont-rulers', 'icofont-square-root', 'icofont-aids', 'icofont-ambulance',
                    'icofont-autism', 'icofont-bandage', 'icofont-bed-patient', 'icofont-blind', 'icofont-blood-drop',
                    'icofont-blood-test', 'icofont-blood', 'icofont-capsule', 'icofont-crutches', 'icofont-dna-alt-1',
                    'icofont-dna', 'icofont-doctor-alt', 'icofont-doctor', 'icofont-drug-pack', 'icofont-drug',
                    'icofont-eye-alt', 'icofont-first-aid-alt', 'icofont-garbage', 'icofont-heart-alt',
                    'icofont-heartbeat', 'icofont-herbal', 'icofont-hospital', 'icofont-icu',
                    'icofont-injection-syringe', 'icofont-laboratory', 'icofont-medical-sign-alt',
                    'icofont-medical-sign', 'icofont-nurse-alt', 'icofont-nurse', 'icofont-nursing-home',
                    'icofont-operation-theater', 'icofont-paralysis-disability', 'icofont-pills',
                    'icofont-prescription', 'icofont-pulse', 'icofont-stethoscope-alt', 'icofont-stethoscope',
                    'icofont-stretcher', 'icofont-surgeon-alt', 'icofont-surgeon', 'icofont-tablets',
                    'icofont-test-bottle', 'icofont-test-tube', 'icofont-thermometer-alt', 'icofont-tooth',
                    'icofont-xray',
                    'icofont-cassette-player', 'icofont-cassette', 'icofont-forward', 'icofont-game', 'icofont-guiter',
                    'icofont-headphone-alt-1', 'icofont-headphone-alt-2', 'icofont-headphone-alt-3',
                    'icofont-listening', 'icofont-megaphone-alt', 'icofont-megaphone', 'icofont-movie',
                    'icofont-mp3-player', 'icofont-multimedia', 'icofont-music-disk', 'icofont-music-note',
                    'icofont-pause', 'icofont-play-alt-1', 'icofont-play-alt-2', 'icofont-play-alt-3',
                    'icofont-play-pause', 'icofont-record', 'icofont-retro-music-disk', 'icofont-rewind',
                    'icofont-song-notes', 'icofont-sound-wave-alt', 'icofont-sound-wave', 'icofont-stop',
                    'icofont-video-alt',
                    'icofont-video-cam', 'icofont-volume-bar', 'icofont-volume-mute', 'icofont-youtube-play',
                    'icofont-boy', 'icofont-business-man-alt-1', 'icofont-business-man-alt-2',
                    'icofont-business-man-alt-3', 'icofont-business-man', 'icofont-funky-man', 'icofont-girl-alt',
                    'icofont-girl', 'icofont-hotel-boy-alt', 'icofont-hotel-boy', 'icofont-man-in-glasses',
                    'icofont-waiter',
                    'icofont-woman-in-glasses', 'icofont-document-search', 'icofont-folder-search',
                    'icofont-home-search', 'icofont-job-search', 'icofont-map-search', 'icofont-restaurant-search',
                    'icofont-search-alt-1', 'icofont-search-alt-2', 'icofont-search', 'icofont-stock-search',
                    'icofont-badminton-birdie', 'icofont-baseball', 'icofont-baseballer',
                    'icofont-basketball-hoop', 'icofont-basketball', 'icofont-billiard-ball', 'icofont-boot-alt-1',
                    'icofont-boot-alt-2', 'icofont-bowling-alt', 'icofont-bowling', 'icofont-canoe',
                    'icofont-cheer-leader', 'icofont-climbing', 'icofont-corner', 'icofont-cyclist',
                    'icofont-dumbbell-alt', 'icofont-dumbbell', 'icofont-field-alt', 'icofont-field',
                    'icofont-football-alt', 'icofont-foul', 'icofont-goal-keeper', 'icofont-goal', 'icofont-golf-alt',
                    'icofont-golf-bag', 'icofont-golf-field', 'icofont-golf', 'icofont-golfer', 'icofont-gym-alt-1',
                    'icofont-gym-alt-2', 'icofont-gym-alt-3', 'icofont-gym', 'icofont-hand-grippers',
                    'icofont-heart-beat-alt', 'icofont-helmet', 'icofont-hockey-alt', 'icofont-hockey',
                    'icofont-ice-skate', 'icofont-jersey-alt', 'icofont-jersey', 'icofont-jumping', 'icofont-kick',
                    'icofont-leg', 'icofont-match-review', 'icofont-medal-alt', 'icofont-muscle-alt', 'icofont-muscle',
                    'icofont-offside', 'icofont-olympic-logo', 'icofont-olympic', 'icofont-padding',
                    'icofont-penalty-card', 'icofont-racer', 'icofont-racing-car', 'icofont-racing-flag-alt',
                    'icofont-racing-flag', 'icofont-racings-wheel', 'icofont-referee', 'icofont-refree-jersey',
                    'icofont-result', 'icofont-rugby-ball', 'icofont-rugby-player', 'icofont-rugby',
                    'icofont-runner-alt-1', 'icofont-runner-alt-2', 'icofont-runner', 'icofont-score-board',
                    'icofont-skiing-man', 'icofont-skydiving-goggles', 'icofont-snow-mobile', 'icofont-steering',
                    'icofont-substitute', 'icofont-swimmer', 'icofont-table-tennis', 'icofont-team-alt', 'icofont-team',
                    'icofont-tennis-player', 'icofont-tennis', 'icofont-time', 'icofont-track', 'icofont-tracking',
                    'icofont-trophy-alt', 'icofont-trophy', 'icofont-volleyball-alt', 'icofont-volleyball-fire',
                    'icofont-volleyball', 'icofont-water-bottle', 'icofont-whisle', 'icofont-win-trophy',
                    'icofont-align-center', 'icofont-align-left', 'icofont-align-right', 'icofont-all-caps',
                    'icofont-bold', 'icofont-brush', 'icofont-clip-board', 'icofont-code-alt', 'icofont-color-bucket',
                    'icofont-color-picker', 'icofont-copy-alt', 'icofont-copy-black', 'icofont-cut',
                    'icofont-delete-alt', 'icofont-edit-alt', 'icofont-eraser-alt', 'icofont-file-alt', 'icofont-font',
                    'icofont-header', 'icofont-indent', 'icofont-italic-alt', 'icofont-justify-all',
                    'icofont-justify-center', 'icofont-justify-left', 'icofont-justify-right', 'icofont-line-height',
                    'icofont-link-alt', 'icofont-listine-dots', 'icofont-listing-box', 'icofont-listing-number',
                    'icofont-marker', 'icofont-outdent', 'icofont-paper-clip', 'icofont-paragraph', 'icofont-pin',
                    'icofont-printer', 'icofont-redo', 'icofont-rotation', 'icofont-save', 'icofont-small-cap',
                    'icofont-strike-through', 'icofont-sub-listing', 'icofont-subscript', 'icofont-superscript',
                    'icofont-table', 'icofont-text-height', 'icofont-text-width', 'icofont-trash', 'icofont-underline',
                    'icofont-undo', 'icofont-unlink', 'icofont-air-balloon', 'icofont-airplane-alt', 'icofont-airplane',
                    'icofont-ambulance-crescent', 'icofont-ambulance-cross', 'icofont-articulated-truck',
                    'icofont-auto-rickshaw', 'icofont-bicycle-alt-1', 'icofont-bicycle-alt-2', 'icofont-bull-dozer',
                    'icofont-bus-alt-1', 'icofont-bus-alt-2', 'icofont-bus-alt-3', 'icofont-cable-car',
                    'icofont-car-alt-1', 'icofont-car-alt-2', 'icofont-car-alt-3', 'icofont-car-alt-4',
                    'icofont-concrete-mixer', 'icofont-delivery-time', 'icofont-excavator', 'icofont-fast-delivery',
                    'icofont-fire-truck-alt', 'icofont-fire-truck', 'icofont-fork-lift', 'icofont-free-delivery',
                    'icofont-golf-cart', 'icofont-helicopter', 'icofont-motor-bike-alt', 'icofont-motor-bike',
                    'icofont-motor-biker', 'icofont-oil-truck', 'icofont-police-car', 'icofont-rickshaw',
                    'icofont-rocket-alt-1', 'icofont-rocket-alt-2', 'icofont-sail-boat', 'icofont-scooter',
                    'icofont-sea-plane', 'icofont-ship-alt', 'icofont-speed-boat', 'icofont-taxi', 'icofont-tow-truck',
                    'icofont-tractor', 'icofont-traffic-light', 'icofont-train-line', 'icofont-train-steam',
                    'icofont-tram', 'icofont-truck-alt', 'icofont-truck-loaded', 'icofont-truck', 'icofont-van-alt',
                    'icofont-van', 'icofont-yacht', 'icofont-5-star-hotel', 'icofont-anchor-alt', 'icofont-beach-bed',
                    'icofont-camping-vest', 'icofont-coconut-alt', 'icofont-direction-sign', 'icofont-hill-side',
                    'icofont-island-alt', 'icofont-long-drive', 'icofont-map-pins', 'icofont-plane-ticket',
                    'icofont-sail-boat-alt-1', 'icofont-sail-boat-alt-2', 'icofont-sandals-female',
                    'icofont-sandals-male', 'icofont-travelling', 'icofont-breakdown', 'icofont-celsius',
                    'icofont-clouds', 'icofont-cloudy', 'icofont-compass-alt', 'icofont-dust', 'icofont-eclipse',
                    'icofont-fahrenheit', 'icofont-forest-fire', 'icofont-full-night', 'icofont-full-sunny',
                    'icofont-hail-night', 'icofont-hail-rainy-night', 'icofont-hail-rainy-sunny', 'icofont-hail-rainy',
                    'icofont-hail-sunny', 'icofont-hail-thunder-night', 'icofont-hail-thunder-sunny',
                    'icofont-hail-thunder', 'icofont-hail', 'icofont-hill-night', 'icofont-hill-sunny', 'icofont-hill',
                    'icofont-hurricane', 'icofont-island', 'icofont-meteor', 'icofont-night', 'icofont-rainy-night',
                    'icofont-rainy-sunny', 'icofont-rainy-thunder', 'icofont-rainy', 'icofont-showy-night-hail',
                    'icofont-snow-temp', 'icofont-snow', 'icofont-snowy-hail', 'icofont-snowy-night-rainy',
                    'icofont-snowy-night', 'icofont-snowy-rainy', 'icofont-snowy-sunny-hail',
                    'icofont-snowy-sunny-rainy', 'icofont-snowy-sunny', 'icofont-snowy-thunder-night',
                    'icofont-snowy-thunder-sunny', 'icofont-snowy-thunder', 'icofont-snowy-windy-night',
                    'icofont-snowy-windy-sunny', 'icofont-snowy-windy', 'icofont-snowy', 'icofont-sun-alt',
                    'icofont-sun-rise', 'icofont-sun-set', 'icofont-sunny-day-temp', 'icofont-sunny',
                    'icofont-thermometer', 'icofont-thinder-light', 'icofont-tornado', 'icofont-umbrella-alt',
                    'icofont-volcano', 'icofont-wave', 'icofont-wind-scale-0', 'icofont-wind-scale-1',
                    'icofont-wind-scale-2', 'icofont-wind-scale-3', 'icofont-wind-scale-4', 'icofont-wind-scale-5',
                    'icofont-wind-scale-6', 'icofont-wind-scale-7', 'icofont-wind-scale-8', 'icofont-wind-scale-9',
                    'icofont-wind-scale-10', 'icofont-wind-scale-11', 'icofont-wind-scale-12', 'icofont-wind-waves',
                    'icofont-wind', 'icofont-windy-hail', 'icofont-windy-night', 'icofont-windy-raining',
                    'icofont-windy-sunny', 'icofont-windy-thunder-raining', 'icofont-windy-thunder', 'icofont-windy',
                    'icofont-addons', 'icofont-address-book', 'icofont-adjust', 'icofont-alarm', 'icofont-anchor',
                    'icofont-archive', 'icofont-at', 'icofont-attachment', 'icofont-audio', 'icofont-auto-mobile',
                    'icofont-automation', 'icofont-baby', 'icofont-badge', 'icofont-bag', 'icofont-ban',
                    'icofont-bank', 'icofont-bar-code', 'icofont-bars', 'icofont-battery-empty', 'icofont-battery-full',
                    'icofont-battery-half', 'icofont-battery-low', 'icofont-beach', 'icofont-beaker', 'icofont-bear',
                    'icofont-beard', 'icofont-bed', 'icofont-bell', 'icofont-beverage', 'icofont-bicycle',
                    'icofont-bill', 'icofont-bin', 'icofont-binary', 'icofont-binoculars', 'icofont-bird',
                    'icofont-birds', 'icofont-black-board', 'icofont-bluetooth', 'icofont-bolt', 'icofont-bomb',
                    'icofont-book-mark', 'icofont-book', 'icofont-boot', 'icofont-box', 'icofont-brain',
                    'icofont-briefcase', 'icofont-broken', 'icofont-bucket', 'icofont-bucket1', 'icofont-bucket2',
                    'icofont-bug', 'icofont-building', 'icofont-bullet', 'icofont-bullhorn', 'icofont-bullseye',
                    'icofont-bus', 'icofont-butterfly', 'icofont-cab', 'icofont-calculator', 'icofont-calendar',
                    'icofont-camera-alt', 'icofont-camera', 'icofont-car', 'icofont-card', 'icofont-cart',
                    'icofont-cc', 'icofont-certificate', 'icofont-charging', 'icofont-chat', 'icofont-check-alt',
                    'icofont-check-circled', 'icofont-check', 'icofont-checked', 'icofont-children-care',
                    'icofont-clock-time', 'icofont-close-circled', 'icofont-close-line-circled',
                    'icofont-close-line-squared-alt', 'icofont-close-line-squared', 'icofont-close-line',
                    'icofont-close-squared-alt', 'icofont-close-squared', 'icofont-close', 'icofont-cloud-download',
                    'icofont-cloud-refresh', 'icofont-cloud-upload', 'icofont-cloud', 'icofont-code-not-allowed',
                    'icofont-code', 'icofont-coffee-cup', 'icofont-comment', 'icofont-compass', 'icofont-computer',
                    'icofont-connection', 'icofont-console', 'icofont-contacts', 'icofont-contrast', 'icofont-copy',
                    'icofont-copyright', 'icofont-credit-card', 'icofont-crop', 'icofont-crown', 'icofont-cube',
                    'icofont-cubes', 'icofont-culinary', 'icofont-dashboard-web', 'icofont-dashboard', 'icofont-data',
                    'icofont-database-add', 'icofont-database-locked', 'icofont-database-remove', 'icofont-database',
                    'icofont-delete', 'icofont-diamond', 'icofont-dice', 'icofont-disabled', 'icofont-disc',
                    'icofont-diskette', 'icofont-document-folder', 'icofont-download-alt', 'icofont-download',
                    'icofont-downloaded', 'icofont-earth', 'icofont-ebook', 'icofont-edit', 'icofont-eject',
                    'icofont-email', 'icofont-envelope-open', 'icofont-envelope', 'icofont-eraser', 'icofont-error',
                    'icofont-exchange', 'icofont-exclamation-circle', 'icofont-exclamation-square',
                    'icofont-exclamation-tringle', 'icofont-exclamation', 'icofont-exit', 'icofont-expand',
                    'icofont-external-link', 'icofont-external', 'icofont-eye-blocked', 'icofont-eye-dropper',
                    'icofont-eye', 'icofont-favourite', 'icofont-fax', 'icofont-female', 'icofont-file',
                    'icofont-film', 'icofont-filter', 'icofont-fire-burn', 'icofont-fire-extinguisher', 'icofont-fire',
                    'icofont-first-aid', 'icofont-flag-alt-1', 'icofont-flag-alt-2', 'icofont-flag',
                    'icofont-flash-light', 'icofont-flash', 'icofont-flask', 'icofont-focus', 'icofont-folder-open',
                    'icofont-folder', 'icofont-foot-print', 'icofont-football-american', 'icofont-football',
                    'icofont-game-console', 'icofont-game-pad', 'icofont-gavel', 'icofont-gear', 'icofont-gears',
                    'icofont-gift', 'icofont-glass', 'icofont-globe', 'icofont-graduate', 'icofont-graffiti',
                    'icofont-grocery', 'icofont-group', 'icofont-hammer', 'icofont-hand', 'icofont-hanger',
                    'icofont-hard-disk', 'icofont-headphone', 'icofont-heart-beat', 'icofont-heart', 'icofont-history',
                    'icofont-home', 'icofont-horn', 'icofont-hotel', 'icofont-hour-glass', 'icofont-id',
                    'icofont-image', 'icofont-inbox', 'icofont-infinite', 'icofont-info-circle', 'icofont-info-square',
                    'icofont-info', 'icofont-institution', 'icofont-interface', 'icofont-invisible', 'icofont-italic',
                    'icofont-jacket', 'icofont-jar', 'icofont-jewlery', 'icofont-karate', 'icofont-key-hole',
                    'icofont-key', 'icofont-keyboard', 'icofont-kid', 'icofont-label', 'icofont-lamp',
                    'icofont-laptop', 'icofont-layers', 'icofont-layout', 'icofont-leaf', 'icofont-leaflet',
                    'icofont-learn', 'icofont-legal', 'icofont-lego', 'icofont-lemon', 'icofont-lens',
                    'icofont-letter', 'icofont-letterbox', 'icofont-library', 'icofont-license', 'icofont-life-bouy',
                    'icofont-life-buoy', 'icofont-life-jacket', 'icofont-life-ring', 'icofont-light-bulb',
                    'icofont-lighter', 'icofont-lightning-ray', 'icofont-like', 'icofont-link', 'icofont-live-support',
                    'icofont-location-arrow', 'icofont-location-pin', 'icofont-lock', 'icofont-login', 'icofont-logout',
                    'icofont-lollipop', 'icofont-look', 'icofont-loop', 'icofont-luggage', 'icofont-lunch',
                    'icofont-lungs', 'icofont-magic-alt', 'icofont-magic', 'icofont-magnet', 'icofont-mail-box',
                    'icofont-mail', 'icofont-male', 'icofont-map', 'icofont-math', 'icofont-maximize',
                    'icofont-measure', 'icofont-medal', 'icofont-medical', 'icofont-medicine', 'icofont-mega-phone',
                    'icofont-memorial', 'icofont-memory-card', 'icofont-mic-mute', 'icofont-mic', 'icofont-micro-chip',
                    'icofont-microphone', 'icofont-microscope', 'icofont-military', 'icofont-mill',
                    'icofont-minus-circle', 'icofont-minus-square', 'icofont-minus', 'icofont-mobile-phone',
                    'icofont-molecule', 'icofont-money', 'icofont-moon', 'icofont-mop', 'icofont-muffin',
                    'icofont-music-alt', 'icofont-music-notes', 'icofont-music', 'icofont-mustache',
                    'icofont-mute-volume', 'icofont-navigation-menu', 'icofont-navigation', 'icofont-network-tower',
                    'icofont-network', 'icofont-news', 'icofont-newspaper', 'icofont-no-smoking', 'icofont-not-allowed',
                    'icofont-notebook', 'icofont-notepad', 'icofont-notification', 'icofont-numbered',
                    'icofont-opposite', 'icofont-optic', 'icofont-options', 'icofont-package', 'icofont-page',
                    'icofont-paint', 'icofont-paper-plane', 'icofont-paperclip', 'icofont-papers', 'icofont-paw',
                    'icofont-pay', 'icofont-pen', 'icofont-pencil', 'icofont-penguin-linux', 'icofont-pestle',
                    'icofont-phone-circle', 'icofont-phone', 'icofont-picture', 'icofont-pie', 'icofont-pine',
                    'icofont-pixels', 'icofont-play', 'icofont-plugin', 'icofont-plus-circle', 'icofont-plus-square',
                    'icofont-plus', 'icofont-polygonal', 'icofont-power', 'icofont-presentation', 'icofont-price',
                    'icofont-print', 'icofont-puzzle', 'icofont-qr-code', 'icofont-queen', 'icofont-question-circle',
                    'icofont-question-square', 'icofont-question', 'icofont-quote-left', 'icofont-quote-right',
                    'icofont-radio', 'icofont-random', 'icofont-recycle', 'icofont-refresh', 'icofont-repair',
                    'icofont-reply-all', 'icofont-reply', 'icofont-resize', 'icofont-responsive', 'icofont-retweet',
                    'icofont-road', 'icofont-robot', 'icofont-rocket', 'icofont-royal', 'icofont-rss-feed',
                    'icofont-safety', 'icofont-sale-discount', 'icofont-satellite', 'icofont-send-mail',
                    'icofont-server', 'icofont-settings', 'icofont-share-alt', 'icofont-share-boxed', 'icofont-share',
                    'icofont-shield', 'icofont-ship', 'icofont-shopping-cart', 'icofont-sign-in', 'icofont-sign-out',
                    'icofont-signal', 'icofont-site-map', 'icofont-smart-phone', 'icofont-soccer', 'icofont-sort-alt',
                    'icofont-sort', 'icofont-space', 'icofont-spanner', 'icofont-speech-comments',
                    'icofont-speed-meter', 'icofont-spinner-alt-1', 'icofont-spinner-alt-2', 'icofont-spinner-alt-3',
                    'icofont-spinner-alt-4', 'icofont-spinner-alt-5', 'icofont-spinner-alt-6', 'icofont-spinner',
                    'icofont-spreadsheet', 'icofont-square', 'icofont-ssl-security', 'icofont-star-alt-1',
                    'icofont-star-alt-2', 'icofont-star', 'icofont-street-view', 'icofont-sun', 'icofont-support-faq',
                    'icofont-tack-pin', 'icofont-tag', 'icofont-tags', 'icofont-tasks', 'icofont-telephone',
                    'icofont-telescope', 'icofont-terminal', 'icofont-thumbs-down', 'icofont-thumbs-up',
                    'icofont-tick-boxed', 'icofont-tick-mark', 'icofont-ticket', 'icofont-tie', 'icofont-toggle-off',
                    'icofont-toggle-on', 'icofont-tools', 'icofont-transparent', 'icofont-tree', 'icofont-umbrella',
                    'icofont-unlock', 'icofont-unlocked', 'icofont-upload-alt', 'icofont-upload', 'icofont-usb-drive',
                    'icofont-usb', 'icofont-vector-path', 'icofont-verification-check', 'icofont-video-clapper',
                    'icofont-video', 'icofont-volume-down', 'icofont-volume-off', 'icofont-volume-up',
                    'icofont-wall-clock', 'icofont-wall', 'icofont-wallet', 'icofont-warning-alt', 'icofont-warning',
                    'icofont-water-drop', 'icofont-web', 'icofont-wheelchair', 'icofont-wifi-alt', 'icofont-wifi',
                    'icofont-world', 'icofont-zigzag', 'icofont-zipped'
                ]


            ];

            /** @var array Arreglo de classes del paquete de íconos FONTAWESOME */
            $fontawesomes = [
                'fa-glass', 'fa-music', 'fa-search', 'fa-envelope-o', 'fa-heart', 'fa-star',
                'fa-star-o', 'fa-user', 'fa-film', 'fa-th-large', 'fa-th', 'fa-th-list',
                'fa-check', 'fa-remove', 'fa-close', 'fa-times','fa-search-plus','fa-search-minus',
                'fa-power-off','fa-signal','fa-gear','fa-cog', 'fa-trash-o','fa-home','fa-file-o',
                'fa-clock-o','fa-road','fa-download','fa-arrow-circle-o-down','fa-arrow-circle-o-up',
                'fa-inbox','fa-play-circle-o','fa-rotate-right','fa-repeat','fa-refresh','fa-list-alt',
                'fa-lock','fa-flag','fa-headphones','fa-volume-off','fa-volume-down','fa-volume-up',
                'fa-qrcode','fa-barcode','fa-tag','fa-tags','fa-book','fa-bookmark','fa-print',
                'fa-camera','fa-font','fa-bold','fa-italic','fa-text-height','fa-text-width',
                'fa-align-left','fa-align-center','fa-align-right','fa-align-justify','fa-list',
                'fa-dedent','fa-outdent','fa-indent','fa-video-camera','fa-photo','fa-image',
                'fa-picture-o','fa-pencil','fa-map-marker','fa-adjust','fa-tint','fa-edit',
                'fa-pencil-square-o','fa-share-square-o','fa-check-square-o','fa-arrows',
                'fa-step-backward','fa-fast-backward','fa-backward','fa-play','fa-pause','fa-stop',
                'fa-forward','fa-fast-forward','fa-step-forward','fa-eject','fa-chevron-left',
                'fa-chevron-right','fa-plus-circle','fa-minus-circle','fa-times-circle','fa-check-circle',
                'fa-question-circle','fa-info-circle','fa-crosshairs','fa-times-circle-o',
                'fa-check-circle-o','fa-ban','fa-arrow-left','fa-arrow-right','fa-arrow-up',
                'fa-arrow-down','fa-mail-forward','fa-share','fa-expand','fa-compress','fa-plus',
                'fa-minus','fa-asterisk','fa-exclamation-circle','fa-gift','fa-leaf','fa-fire','fa-eye',
                'fa-eye-slash','fa-warning','fa-exclamation-triangle','fa-plane','fa-calendar',
                'fa-random','fa-comment','fa-magnet','fa-chevron-up','fa-chevron-down','fa-retweet',
                'fa-shopping-cart','fa-folder','fa-folder-open','fa-arrows-v','fa-arrows-h',
                'fa-bar-chart-o','fa-bar-chart','fa-twitter-square','fa-facebook-square',
                'fa-camera-retro','fa-key','fa-gears','fa-cogs','fa-comments','fa-thumbs-o-up',
                'fa-thumbs-o-down','fa-star-half','fa-heart-o','fa-sign-out','fa-linkedin-square',
                'fa-thumb-tack','fa-external-link','fa-sign-in','fa-trophy','fa-github-square',
                'fa-upload','fa-lemon-o','fa-phone','fa-square-o','fa-bookmark-o','fa-phone-square',
                'fa-twitter','fa-facebook-f','fa-facebook','fa-github','fa-unlock','fa-credit-card',
                'fa-feed','fa-rss','fa-hdd-o','fa-bullhorn','fa-bell','fa-certificate','fa-hand-o-right',
                'fa-hand-o-left','fa-hand-o-up','fa-hand-o-down','fa-arrow-circle-left',
                'fa-arrow-circle-right','fa-arrow-circle-up','fa-arrow-circle-down','fa-globe',
                'fa-wrench','fa-tasks','fa-filter','fa-briefcase','fa-arrows-alt','fa-group','fa-users',
                'fa-chain','fa-link','fa-cloud','fa-flask','fa-cut','fa-scissors','fa-copy','fa-files-o',
                'fa-paperclip','fa-save','fa-floppy-o','fa-square','fa-navicon','fa-reorder','fa-bars',
                'fa-list-ul','fa-list-ol','fa-strikethrough','fa-underline','fa-table','fa-magic',
                'fa-truck','fa-pinterest','fa-pinterest-square','fa-google-plus-square','fa-google-plus',
                'fa-money','fa-caret-down','fa-caret-up','fa-caret-left','fa-caret-right','fa-columns',
                'fa-unsorted','fa-sort','fa-sort-down','fa-sort-desc','fa-sort-up','fa-sort-asc',
                'fa-envelope','fa-linkedin','fa-rotate-left','fa-undo','fa-legal','fa-gavel',
                'fa-dashboard','fa-tachometer','fa-comment-o','fa-comments-o','fa-flash','fa-bolt',
                'fa-sitemap','fa-umbrella','fa-paste','fa-clipboard','fa-lightbulb-o','fa-exchange',
                'fa-cloud-download','fa-cloud-upload','fa-user-md','fa-stethoscope','fa-suitcase',
                'fa-bell-o','fa-coffee','fa-cutlery','fa-file-text-o','fa-building-o','fa-hospital-o',
                'fa-ambulance','fa-medkit','fa-fighter-jet','fa-beer','fa-h-square','fa-plus-square',
                'fa-angle-double-left','fa-angle-double-right','fa-angle-double-up',
                'fa-angle-double-down','fa-angle-left','fa-angle-right','fa-angle-up','fa-angle-down',
                'fa-desktop','fa-laptop','fa-tablet','fa-mobile-phone','fa-mobile','fa-circle-o',
                'fa-quote-left','fa-quote-right','fa-spinner','fa-circle','fa-mail-reply','fa-reply',
                'fa-github-alt','fa-folder-o','fa-folder-open-o','fa-smile-o','fa-frown-o','fa-meh-o',
                'fa-gamepad','fa-keyboard-o','fa-flag-o','fa-flag-checkered','fa-terminal','fa-code',
                'fa-mail-reply-all','fa-reply-all','fa-star-half-empty','fa-star-half-full',
                'fa-star-half-o','fa-location-arrow','fa-crop','fa-code-fork','fa-unlink',
                'fa-chain-broken','fa-question','fa-info','fa-exclamation','fa-superscript',
                'fa-subscript','fa-eraser','fa-puzzle-piece','fa-microphone','fa-microphone-slash',
                'fa-shield','fa-calendar-o','fa-fire-extinguisher','fa-rocket','fa-maxcdn',
                'fa-chevron-circle-left','fa-chevron-circle-right','fa-chevron-circle-up',
                'fa-chevron-circle-down','fa-html5','fa-css3','fa-anchor','fa-unlock-alt',
                'fa-bullseye','fa-ellipsis-h','fa-ellipsis-v','fa-rss-square','fa-play-circle',
                'fa-ticket','fa-minus-square','fa-minus-square-o','fa-level-up','fa-level-down',
                'fa-check-square','fa-pencil-square','fa-external-link-square','fa-share-square',
                'fa-compass','fa-toggle-down','fa-caret-square-o-down','fa-toggle-up',
                'fa-caret-square-o-up','fa-toggle-right','fa-caret-square-o-right','fa-euro','fa-eur',
                'fa-gbp','fa-dollar','fa-usd','fa-rupee','fa-inr','fa-cny','fa-rmb','fa-yen','fa-jpy',
                'fa-ruble','fa-rouble','fa-rub','fa-won','fa-krw','fa-bitcoin','fa-btc','fa-file',
                'fa-file-text','fa-sort-alpha-asc','fa-sort-alpha-desc','fa-sort-amount-asc',
                'fa-sort-amount-desc','fa-sort-numeric-asc','fa-sort-numeric-desc','fa-thumbs-up',
                'fa-thumbs-down','fa-youtube-square','fa-youtube','fa-xing','fa-xing-square',
                'fa-youtube-play','fa-dropbox','fa-stack-overflow','fa-instagram','fa-flickr','fa-adn',
                'fa-bitbucket','fa-bitbucket-square','fa-tumblr','fa-tumblr-square','fa-long-arrow-down',
                'fa-long-arrow-up','fa-long-arrow-left','fa-long-arrow-right','fa-apple','fa-windows',
                'fa-android','fa-linux','fa-dribbble','fa-skype','fa-foursquare','fa-trello','fa-female',
                'fa-male','fa-gittip','fa-gratipay','fa-sun-o','fa-moon-o','fa-archive','fa-bug','fa-vk',
                'fa-weibo','fa-renren','fa-pagelines','fa-stack-exchange','fa-arrow-circle-o-right',
                'fa-arrow-circle-o-left','fa-toggle-left','fa-caret-square-o-left','fa-dot-circle-o',
                'fa-wheelchair','fa-vimeo-square','fa-turkish-lira','fa-try','fa-plus-square-o',
                'fa-space-shuttle','fa-slack','fa-envelope-square','fa-wordpress','fa-openid',
                'fa-institution','fa-bank','fa-university','fa-mortar-board','fa-graduation-cap',
                'fa-yahoo','fa-google','fa-reddit','fa-reddit-square','fa-stumbleupon-circle',
                'fa-stumbleupon','fa-delicious','fa-digg','fa-pied-piper-pp','fa-pied-piper-alt',
                'fa-drupal','fa-joomla','fa-language','fa-fax','fa-building','fa-child','fa-paw',
                'fa-spoon','fa-cube','fa-cubes','fa-behance','fa-behance-square','fa-steam',
                'fa-steam-square','fa-recycle','fa-automobile','fa-car','fa-cab','fa-taxi','fa-tree',
                'fa-spotify','fa-deviantart','fa-soundcloud','fa-database','fa-file-pdf-o',
                'fa-file-word-o','fa-file-excel-o','fa-file-powerpoint-o','fa-file-photo-o',
                'fa-file-picture-o','fa-file-image-o','fa-file-zip-o','fa-file-archive-o',
                'fa-file-sound-o','fa-file-audio-o','fa-file-movie-o','fa-file-video-o','fa-file-code-o',
                'fa-vine','fa-codepen','fa-jsfiddle','fa-life-bouy','fa-life-buoy','fa-life-saver',
                'fa-support','fa-life-ring','fa-circle-o-notch','fa-ra','fa-resistance','fa-rebel',
                'fa-ge','fa-empire','fa-git-square','fa-git','fa-y-combinator-square','fa-yc-square',
                'fa-hacker-news','fa-tencent-weibo','fa-qq','fa-wechat','fa-weixin','fa-send',
                'fa-paper-plane','fa-send-o','fa-paper-plane-o','fa-history','fa-circle-thin','fa-header',
                'fa-paragraph','fa-sliders','fa-share-alt','fa-share-alt-square','fa-bomb',
                'fa-soccer-ball-o','fa-futbol-o','fa-tty','fa-binoculars','fa-plug','fa-slideshare',
                'fa-twitch','fa-yelp','fa-newspaper-o','fa-wifi','fa-calculator','fa-paypal',
                'fa-google-wallet','fa-cc-visa','fa-cc-mastercard','fa-cc-discover','fa-cc-amex',
                'fa-cc-paypal','fa-cc-stripe','fa-bell-slash','fa-bell-slash-o','fa-trash','fa-copyright',
                'fa-at','fa-eyedropper','fa-paint-brush','fa-birthday-cake','fa-area-chart',
                'fa-pie-chart','fa-line-chart','fa-lastfm','fa-lastfm-square','fa-toggle-off',
                'fa-toggle-on','fa-bicycle','fa-bus','fa-ioxhost','fa-angellist','fa-cc','fa-shekel',
                'fa-sheqel','fa-ils','fa-meanpath','fa-buysellads','fa-connectdevelop','fa-dashcube',
                'fa-forumbee','fa-leanpub','fa-sellsy','fa-shirtsinbulk','fa-simplybuilt','fa-skyatlas',
                'fa-cart-plus','fa-cart-arrow-down','fa-diamond','fa-ship','fa-user-secret',
                'fa-motorcycle','fa-street-view','fa-heartbeat','fa-venus','fa-mars','fa-mercury',
                'fa-intersex','fa-transgender','fa-transgender-alt','fa-venus-double','fa-mars-double',
                'fa-venus-mars','fa-mars-stroke','fa-mars-stroke-v','fa-mars-stroke-h','fa-neuter',
                'fa-genderless','fa-facebook-official','fa-pinterest-p','fa-whatsapp','fa-server',
                'fa-user-plus','fa-user-times','fa-hotel','fa-bed','fa-viacoin','fa-train','fa-subway',
                'fa-medium','fa-yc','fa-y-combinator','fa-optin-monster','fa-opencart','fa-expeditedssl',
                'fa-battery-4','fa-battery','fa-battery-full','fa-battery-3','fa-battery-three-quarters',
                'fa-battery-2','fa-battery-half','fa-battery-1','fa-battery-quarter','fa-battery-0',
                'fa-battery-empty','fa-mouse-pointer','fa-i-cursor','fa-object-group','fa-object-ungroup',
                'fa-sticky-note','fa-sticky-note-o','fa-cc-jcb','fa-cc-diners-club','fa-clone',
                'fa-balance-scale','fa-hourglass-o','fa-hourglass-1','fa-hourglass-start',
                'fa-hourglass-2','fa-hourglass-half','fa-hourglass-3','fa-hourglass-end','fa-hourglass',
                'fa-hand-grab-o','fa-hand-rock-o','fa-hand-stop-o','fa-hand-paper-o','fa-hand-scissors-o',
                'fa-hand-lizard-o','fa-hand-spock-o','fa-hand-pointer-o','fa-hand-peace-o','fa-trademark',
                'fa-registered','fa-creative-commons','fa-gg','fa-gg-circle','fa-tripadvisor',
                'fa-odnoklassniki','fa-odnoklassniki-square','fa-get-pocket','fa-wikipedia-w','fa-safari',
                'fa-chrome','fa-firefox','fa-opera','fa-internet-explorer','fa-tv','fa-television',
                'fa-contao','fa-500px','fa-amazon','fa-calendar-plus-o','fa-calendar-minus-o',
                'fa-calendar-times-o','fa-calendar-check-o','fa-industry','fa-map-pin','fa-map-signs',
                'fa-map-o','fa-map','fa-commenting','fa-commenting-o','fa-houzz','fa-vimeo',
                'fa-black-tie','fa-fonticons','fa-reddit-alien','fa-edge','fa-credit-card-alt',
                'fa-codiepie','fa-modx','fa-fort-awesome','fa-usb','fa-product-hunt','fa-mixcloud',
                'fa-scribd','fa-pause-circle','fa-pause-circle-o','fa-stop-circle','fa-stop-circle-o',
                'fa-shopping-bag','fa-shopping-basket','fa-hashtag','fa-bluetooth','fa-bluetooth-b',
                'fa-percent','fa-gitlab','fa-wpbeginner','fa-wpforms','fa-envira','fa-universal-access',
                'fa-wheelchair-alt','fa-question-circle-o','fa-blind','fa-audio-description',
                'fa-volume-control-phone','fa-braille','fa-assistive-listening-systems',
                'fa-asl-interpreting','fa-american-sign-language-interpreting','fa-deafness',
                'fa-hard-of-hearing','fa-deaf','fa-glide','fa-glide-g','fa-signing','fa-sign-language',
                'fa-low-vision','fa-viadeo','fa-viadeo-square','fa-snapchat','fa-snapchat-ghost',
                'fa-snapchat-square','fa-pied-piper','fa-first-order','fa-yoast','fa-themeisle',
                'fa-google-plus-circle','fa-google-plus-official','fa-fa','fa-font-awesome',
                'fa-handshake-o','fa-envelope-open','fa-envelope-open-o','fa-linode','fa-address-book',
                'fa-address-book-o','fa-vcard','fa-address-card','fa-vcard-o','fa-address-card-o',
                'fa-user-circle','fa-user-circle-o','fa-user-o','fa-id-badge','fa-drivers-license',
                'fa-id-card','fa-drivers-license-o','fa-id-card-o','fa-quora','fa-free-code-camp',
                'fa-telegram','fa-thermometer-4','fa-thermometer','fa-thermometer-full',
                'fa-thermometer-3','fa-thermometer-three-quarters','fa-thermometer-2',
                'fa-thermometer-half','fa-thermometer-1','fa-thermometer-quarter','fa-thermometer-0',
                'fa-thermometer-empty','fa-shower','fa-bathtub','fa-s15','fa-bath','fa-podcast',
                'fa-window-maximize','fa-window-minimize','fa-window-restore','fa-times-rectangle',
                'fa-window-close','fa-times-rectangle-o','fa-window-close-o','fa-bandcamp','fa-grav',
                'fa-etsy','fa-imdb','fa-ravelry','fa-eercast','fa-microchip','fa-snowflake-o',
                'fa-superpowers','fa-wpexplorer','fa-meetup'
            ];

            /** @var array Arreglo de classes del paquete de íconos IONICONS */
            $ionicons = [
                'ion-alert', 'ion-alert-circled', 'ion-android-add', 'ion-android-add-circle',
                'ion-android-alarm-clock', 'ion-android-alert', 'ion-android-apps',
                'ion-android-archive', 'ion-android-arrow-back', 'ion-android-arrow-down',
                'ion-android-arrow-dropdown', 'ion-android-arrow-dropdown-circle',
                'ion-android-arrow-dropleft', 'ion-android-arrow-dropleft-circle',
                'ion-android-arrow-dropright', 'ion-android-arrow-dropright-circle',
                'ion-android-arrow-dropup', 'ion-android-arrow-dropup-circle',
                'ion-android-arrow-forward', 'ion-android-arrow-up', 'ion-android-attach',
                'ion-android-bar', 'ion-android-bicycle', 'ion-android-boat',
                'ion-android-bookmark', 'ion-android-bulb', 'ion-android-bus',
                'ion-android-calendar', 'ion-android-call', 'ion-android-camera',
                'ion-android-cancel', 'ion-android-car', 'ion-android-cart', 'ion-android-chat',
                'ion-android-checkbox', 'ion-android-checkbox-blank',
                'ion-android-checkbox-outline', 'ion-android-checkbox-outline-blank',
                'ion-android-checkmark-circle', 'ion-android-clipboard', 'ion-android-close',
                'ion-android-cloud', 'ion-android-cloud-circle', 'ion-android-cloud-done',
                'ion-android-cloud-outline', 'ion-android-color-palette', 'ion-android-compass',
                'ion-android-contact', 'ion-android-contacts', 'ion-android-contract',
                'ion-android-create', 'ion-android-delete', 'ion-android-desktop',
                'ion-android-document', 'ion-android-done', 'ion-android-done-all',
                'ion-android-download', 'ion-android-drafts', 'ion-android-exit',
                'ion-android-expand', 'ion-android-favorite', 'ion-android-favorite-outline',
                'ion-android-film', 'ion-android-folder', 'ion-android-folder-open',
                'ion-android-funnel', 'ion-android-globe', 'ion-android-hand',
                'ion-android-hangout', 'ion-android-happy', 'ion-android-home',
                'ion-android-image', 'ion-android-laptop', 'ion-android-list',
                'ion-android-locate', 'ion-android-lock', 'ion-android-mail', 'ion-android-map',
                'ion-android-menu', 'ion-android-microphone', 'ion-android-microphone-off',
                'ion-android-more-horizontal', 'ion-android-more-vertical', 'ion-android-navigate',
                'ion-android-notifications', 'ion-android-notifications-none',
                'ion-android-notifications-off', 'ion-android-open', 'ion-android-options',
                'ion-android-people', 'ion-android-person', 'ion-android-person-add',
                'ion-android-phone-landscape', 'ion-android-phone-portrait', 'ion-android-pin',
                'ion-android-plane', 'ion-android-playstore', 'ion-android-print',
                'ion-android-radio-button-off', 'ion-android-radio-button-on',
                'ion-android-refresh', 'ion-android-remove', 'ion-android-remove-circle',
                'ion-android-restaurant', 'ion-android-sad', 'ion-android-search',
                'ion-android-send', 'ion-android-settings', 'ion-android-share',
                'ion-android-share-alt', 'ion-android-star', 'ion-android-star-half',
                'ion-android-star-outline', 'ion-android-stopwatch', 'ion-android-subway',
                'ion-android-sunny', 'ion-android-sync', 'ion-android-textsms', 'ion-android-time',
                'ion-android-train', 'ion-android-unlock', 'ion-android-upload',
                'ion-android-volume-down', 'ion-android-volume-mute', 'ion-android-volume-off',
                'ion-android-volume-up', 'ion-android-walk', 'ion-android-warning',
                'ion-android-watch', 'ion-android-wifi', 'ion-aperture', 'ion-archive',
                'ion-arrow-down-a', 'ion-arrow-down-b', 'ion-arrow-down-c', 'ion-arrow-expand',
                'ion-arrow-graph-down-left', 'ion-arrow-graph-down-right',
                'ion-arrow-graph-up-left', 'ion-arrow-graph-up-right', 'ion-arrow-left-a',
                'ion-arrow-left-b', 'ion-arrow-left-c', 'ion-arrow-move', 'ion-arrow-resize',
                'ion-arrow-return-left', 'ion-arrow-return-right', 'ion-arrow-right-a',
                'ion-arrow-right-b', 'ion-arrow-right-c', 'ion-arrow-shrink', 'ion-arrow-swap',
                'ion-arrow-up-a', 'ion-arrow-up-b', 'ion-arrow-up-c', 'ion-asterisk', 'ion-at',
                'ion-backspace', 'ion-backspace-outline', 'ion-bag', 'ion-battery-charging',
                'ion-battery-empty', 'ion-battery-full', 'ion-battery-half', 'ion-battery-low',
                'ion-beaker', 'ion-beer', 'ion-bluetooth', 'ion-bonfire', 'ion-bookmark',
                'ion-bowtie', 'ion-briefcase', 'ion-bug', 'ion-calculator', 'ion-calendar',
                'ion-camera', 'ion-card', 'ion-cash', 'ion-chatbox', 'ion-chatbox-working',
                'ion-chatboxes', 'ion-chatbubble', 'ion-chatbubble-working', 'ion-chatbubbles',
                'ion-checkmark', 'ion-checkmark-circled', 'ion-checkmark-round',
                'ion-chevron-down', 'ion-chevron-left', 'ion-chevron-right', 'ion-chevron-up',
                'ion-clipboard', 'ion-clock', 'ion-close', 'ion-close-circled', 'ion-close-round',
                'ion-closed-captioning', 'ion-cloud', 'ion-code', 'ion-code-download',
                'ion-code-working', 'ion-coffee', 'ion-compass', 'ion-compose',
                'ion-connection-bars', 'ion-contrast', 'ion-crop', 'ion-cube', 'ion-disc',
                'ion-document', 'ion-document-text', 'ion-drag', 'ion-earth', 'ion-easel',
                'ion-edit', 'ion-egg', 'ion-eject', 'ion-email', 'ion-email-unread',
                'ion-erlenmeyer-flask', 'ion-erlenmeyer-flask-bubbles', 'ion-eye',
                'ion-eye-disabled', 'ion-female', 'ion-filing', 'ion-film-marker', 'ion-fireball',
                'ion-flag', 'ion-flame', 'ion-flash', 'ion-flash-off', 'ion-folder', 'ion-fork',
                'ion-fork-repo', 'ion-forward', 'ion-funnel', 'ion-gear-a', 'ion-gear-b',
                'ion-grid', 'ion-hammer', 'ion-happy', 'ion-happy-outline', 'ion-headphone',
                'ion-heart', 'ion-heart-broken', 'ion-help', 'ion-help-buoy', 'ion-help-circled',
                'ion-home', 'ion-icecream', 'ion-image', 'ion-images', 'ion-information',
                'ion-information-circled', 'ion-ionic', 'ion-ios-alarm', 'ion-ios-alarm-outline',
                'ion-ios-albums', 'ion-ios-albums-outline', 'ion-ios-americanfootball',
                'ion-ios-americanfootball-outline', 'ion-ios-analytics',
                'ion-ios-analytics-outline', 'ion-ios-arrow-back', 'ion-ios-arrow-down',
                'ion-ios-arrow-forward', 'ion-ios-arrow-left', 'ion-ios-arrow-right',
                'ion-ios-arrow-thin-down', 'ion-ios-arrow-thin-left', 'ion-ios-arrow-thin-right',
                'ion-ios-arrow-thin-up', 'ion-ios-arrow-up', 'ion-ios-at', 'ion-ios-at-outline',
                'ion-ios-barcode', 'ion-ios-barcode-outline', 'ion-ios-baseball',
                'ion-ios-baseball-outline', 'ion-ios-basketball', 'ion-ios-basketball-outline',
                'ion-ios-bell', 'ion-ios-bell-outline', 'ion-ios-body', 'ion-ios-body-outline',
                'ion-ios-bolt', 'ion-ios-bolt-outline', 'ion-ios-book', 'ion-ios-book-outline',
                'ion-ios-bookmarks', 'ion-ios-bookmarks-outline', 'ion-ios-box',
                'ion-ios-box-outline', 'ion-ios-briefcase', 'ion-ios-briefcase-outline',
                'ion-ios-browsers', 'ion-ios-browsers-outline', 'ion-ios-calculator',
                'ion-ios-calculator-outline', 'ion-ios-calendar', 'ion-ios-calendar-outline',
                'ion-ios-camera', 'ion-ios-camera-outline', 'ion-ios-cart', 'ion-ios-cart-outline',
                'ion-ios-chatboxes', 'ion-ios-chatboxes-outline', 'ion-ios-chatbubble',
                'ion-ios-chatbubble-outline', 'ion-ios-checkmark', 'ion-ios-checkmark-empty',
                'ion-ios-checkmark-outline', 'ion-ios-circle-filled', 'ion-ios-circle-outline',
                'ion-ios-clock', 'ion-ios-clock-outline', 'ion-ios-close', 'ion-ios-close-empty',
                'ion-ios-close-outline', 'ion-ios-cloud', 'ion-ios-cloud-download',
                'ion-ios-cloud-download-outline', 'ion-ios-cloud-outline', 'ion-ios-cloud-upload',
                'ion-ios-cloud-upload-outline', 'ion-ios-cloudy', 'ion-ios-cloudy-night',
                'ion-ios-cloudy-night-outline', 'ion-ios-cloudy-outline', 'ion-ios-cog',
                'ion-ios-cog-outline', 'ion-ios-color-filter', 'ion-ios-color-filter-outline',
                'ion-ios-color-wand', 'ion-ios-color-wand-outline', 'ion-ios-compose',
                'ion-ios-compose-outline', 'ion-ios-contact', 'ion-ios-contact-outline',
                'ion-ios-copy', 'ion-ios-copy-outline', 'ion-ios-crop', 'ion-ios-crop-strong',
                'ion-ios-download', 'ion-ios-download-outline', 'ion-ios-drag', 'ion-ios-email',
                'ion-ios-email-outline', 'ion-ios-eye', 'ion-ios-eye-outline',
                'ion-ios-fastforward', 'ion-ios-fastforward-outline', 'ion-ios-filing',
                'ion-ios-filing-outline', 'ion-ios-film', 'ion-ios-film-outline', 'ion-ios-flag',
                'ion-ios-flag-outline', 'ion-ios-flame', 'ion-ios-flame-outline', 'ion-ios-flask',
                'ion-ios-flask-outline', 'ion-ios-flower', 'ion-ios-flower-outline',
                'ion-ios-folder', 'ion-ios-folder-outline', 'ion-ios-football',
                'ion-ios-football-outline', 'ion-ios-game-controller-a',
                'ion-ios-game-controller-a-outline', 'ion-ios-game-controller-b',
                'ion-ios-game-controller-b-outline', 'ion-ios-gear', 'ion-ios-gear-outline',
                'ion-ios-glasses', 'ion-ios-glasses-outline', 'ion-ios-grid-view',
                'ion-ios-grid-view-outline', 'ion-ios-heart', 'ion-ios-heart-outline',
                'ion-ios-help', 'ion-ios-help-empty', 'ion-ios-help-outline', 'ion-ios-home',
                'ion-ios-home-outline', 'ion-ios-infinite', 'ion-ios-infinite-outline',
                'ion-ios-information', 'ion-ios-information-empty', 'ion-ios-information-outline',
                'ion-ios-ionic-outline', 'ion-ios-keypad', 'ion-ios-keypad-outline',
                'ion-ios-lightbulb', 'ion-ios-lightbulb-outline', 'ion-ios-list',
                'ion-ios-list-outline', 'ion-ios-location', 'ion-ios-location-outline',
                'ion-ios-locked', 'ion-ios-locked-outline', 'ion-ios-loop', 'ion-ios-loop-strong',
                'ion-ios-medical', 'ion-ios-medical-outline', 'ion-ios-medkit',
                'ion-ios-medkit-outline', 'ion-ios-mic', 'ion-ios-mic-off', 'ion-ios-mic-outline',
                'ion-ios-minus', 'ion-ios-minus-empty', 'ion-ios-minus-outline', 'ion-ios-monitor',
                'ion-ios-monitor-outline', 'ion-ios-moon', 'ion-ios-moon-outline', 'ion-ios-more',
                'ion-ios-more-outline', 'ion-ios-musical-note', 'ion-ios-musical-notes',
                'ion-ios-navigate', 'ion-ios-navigate-outline', 'ion-ios-nutrition',
                'ion-ios-nutrition-outline', 'ion-ios-paper', 'ion-ios-paper-outline',
                'ion-ios-paperplane', 'ion-ios-paperplane-outline', 'ion-ios-partlysunny',
                'ion-ios-partlysunny-outline', 'ion-ios-pause', 'ion-ios-pause-outline',
                'ion-ios-paw', 'ion-ios-paw-outline', 'ion-ios-people', 'ion-ios-people-outline',
                'ion-ios-person', 'ion-ios-person-outline', 'ion-ios-personadd',
                'ion-ios-personadd-outline', 'ion-ios-photos', 'ion-ios-photos-outline',
                'ion-ios-pie', 'ion-ios-pie-outline', 'ion-ios-pint', 'ion-ios-pint-outline',
                'ion-ios-play', 'ion-ios-play-outline', 'ion-ios-plus', 'ion-ios-plus-empty',
                'ion-ios-plus-outline', 'ion-ios-pricetag', 'ion-ios-pricetag-outline',
                'ion-ios-pricetags', 'ion-ios-pricetags-outline', 'ion-ios-printer',
                'ion-ios-printer-outline', 'ion-ios-pulse', 'ion-ios-pulse-strong',
                'ion-ios-rainy', 'ion-ios-rainy-outline', 'ion-ios-recording',
                'ion-ios-recording-outline', 'ion-ios-redo', 'ion-ios-redo-outline',
                'ion-ios-refresh', 'ion-ios-refresh-empty', 'ion-ios-refresh-outline',
                'ion-ios-reload', 'ion-ios-reverse-camera', 'ion-ios-reverse-camera-outline',
                'ion-ios-rewind', 'ion-ios-rewind-outline', 'ion-ios-rose', 'ion-ios-rose-outline',
                'ion-ios-search', 'ion-ios-search-strong', 'ion-ios-settings',
                'ion-ios-settings-strong', 'ion-ios-shuffle', 'ion-ios-shuffle-strong',
                'ion-ios-skipbackward', 'ion-ios-skipbackward-outline', 'ion-ios-skipforward',
                'ion-ios-skipforward-outline', 'ion-ios-snowy', 'ion-ios-speedometer',
                'ion-ios-speedometer-outline', 'ion-ios-star', 'ion-ios-star-half',
                'ion-ios-star-outline', 'ion-ios-stopwatch', 'ion-ios-stopwatch-outline',
                'ion-ios-sunny', 'ion-ios-sunny-outline', 'ion-ios-telephone',
                'ion-ios-telephone-outline', 'ion-ios-tennisball', 'ion-ios-tennisball-outline',
                'ion-ios-thunderstorm', 'ion-ios-thunderstorm-outline', 'ion-ios-time',
                'ion-ios-time-outline', 'ion-ios-timer', 'ion-ios-timer-outline', 'ion-ios-toggle',
                'ion-ios-toggle-outline', 'ion-ios-trash', 'ion-ios-trash-outline', 'ion-ios-undo',
                'ion-ios-undo-outline', 'ion-ios-unlocked', 'ion-ios-unlocked-outline',
                'ion-ios-upload', 'ion-ios-upload-outline', 'ion-ios-videocam',
                'ion-ios-videocam-outline', 'ion-ios-volume-high', 'ion-ios-volume-low',
                'ion-ios-wineglass', 'ion-ios-wineglass-outline', 'ion-ios-world',
                'ion-ios-world-outline', 'ion-ipad', 'ion-iphone', 'ion-ipod', 'ion-jet',
                'ion-key', 'ion-knife', 'ion-laptop', 'ion-leaf', 'ion-levels', 'ion-lightbulb',
                'ion-link', 'ion-load-a', 'ion-load-b', 'ion-load-c', 'ion-load-d', 'ion-location',
                'ion-lock-combination', 'ion-locked', 'ion-log-in', 'ion-log-out', 'ion-loop',
                'ion-magnet', 'ion-male', 'ion-man', 'ion-map', 'ion-medkit', 'ion-merge',
                'ion-mic-a', 'ion-mic-b', 'ion-mic-c', 'ion-minus', 'ion-minus-circled',
                'ion-minus-round', 'ion-model-s', 'ion-monitor', 'ion-more', 'ion-mouse',
                'ion-music-note', 'ion-navicon', 'ion-navicon-round', 'ion-navigate',
                'ion-network', 'ion-no-smoking', 'ion-nuclear', 'ion-outlet', 'ion-paintbrush',
                'ion-paintbucket', 'ion-paper-airplane', 'ion-paperclip', 'ion-pause',
                'ion-person', 'ion-person-add', 'ion-person-stalker', 'ion-pie-graph', 'ion-pin',
                'ion-pinpoint', 'ion-pizza', 'ion-plane', 'ion-planet', 'ion-play',
                'ion-playstation', 'ion-plus', 'ion-plus-circled', 'ion-plus-round', 'ion-podium',
                'ion-pound', 'ion-power', 'ion-pricetag', 'ion-pricetags', 'ion-printer',
                'ion-pull-request', 'ion-qr-scanner', 'ion-quote', 'ion-radio-waves', 'ion-record',
                'ion-refresh', 'ion-reply', 'ion-reply-all', 'ion-ribbon-a', 'ion-ribbon-b',
                'ion-sad', 'ion-sad-outline', 'ion-scissors', 'ion-search', 'ion-settings',
                'ion-share', 'ion-shuffle', 'ion-skip-backward', 'ion-skip-forward',
                'ion-social-android', 'ion-social-android-outline', 'ion-social-angular',
                'ion-social-angular-outline', 'ion-social-apple', 'ion-social-apple-outline',
                'ion-social-bitcoin', 'ion-social-bitcoin-outline', 'ion-social-buffer',
                'ion-social-buffer-outline', 'ion-social-chrome', 'ion-social-chrome-outline',
                'ion-social-codepen', 'ion-social-codepen-outline', 'ion-social-css3',
                'ion-social-css3-outline', 'ion-social-designernews',
                'ion-social-designernews-outline', 'ion-social-dribbble',
                'ion-social-dribbble-outline', 'ion-social-dropbox', 'ion-social-dropbox-outline',
                'ion-social-euro', 'ion-social-euro-outline', 'ion-social-facebook',
                'ion-social-facebook-outline', 'ion-social-foursquare',
                'ion-social-foursquare-outline', 'ion-social-freebsd-devil', 'ion-social-github',
                'ion-social-github-outline', 'ion-social-google', 'ion-social-google-outline',
                'ion-social-googleplus', 'ion-social-googleplus-outline', 'ion-social-hackernews',
                'ion-social-hackernews-outline', 'ion-social-html5', 'ion-social-html5-outline',
                'ion-social-instagram', 'ion-social-instagram-outline', 'ion-social-javascript',
                'ion-social-javascript-outline', 'ion-social-linkedin',
                'ion-social-linkedin-outline', 'ion-social-markdown', 'ion-social-nodejs',
                'ion-social-octocat', 'ion-social-pinterest', 'ion-social-pinterest-outline',
                'ion-social-python', 'ion-social-reddit', 'ion-social-reddit-outline',
                'ion-social-rss', 'ion-social-rss-outline', 'ion-social-sass', 'ion-social-skype',
                'ion-social-skype-outline', 'ion-social-snapchat', 'ion-social-snapchat-outline',
                'ion-social-tumblr', 'ion-social-tumblr-outline', 'ion-social-tux',
                'ion-social-twitch', 'ion-social-twitch-outline', 'ion-social-twitter',
                'ion-social-twitter-outline', 'ion-social-usd', 'ion-social-usd-outline',
                'ion-social-vimeo', 'ion-social-vimeo-outline', 'ion-social-whatsapp',
                'ion-social-whatsapp-outline', 'ion-social-windows', 'ion-social-windows-outline',
                'ion-social-wordpress', 'ion-social-wordpress-outline', 'ion-social-yahoo',
                'ion-social-yahoo-outline', 'ion-social-yen', 'ion-social-yen-outline',
                'ion-social-youtube', 'ion-social-youtube-outline', 'ion-soup-can',
                'ion-soup-can-outline', 'ion-speakerphone', 'ion-speedometer', 'ion-spoon',
                'ion-star', 'ion-stats-bars', 'ion-steam', 'ion-stop', 'ion-thermometer',
                'ion-thumbsdown', 'ion-thumbsup', 'ion-toggle', 'ion-toggle-filled',
                'ion-transgender', 'ion-trash-a', 'ion-trash-b', 'ion-trophy', 'ion-tshirt',
                'ion-tshirt-outline', 'ion-umbrella', 'ion-university', 'ion-unlocked',
                'ion-upload', 'ion-usb', 'ion-videocamera', 'ion-volume-high', 'ion-volume-low',
                'ion-volume-medium', 'ion-volume-mute', 'ion-wand', 'ion-waterdrop', 'ion-wifi',
                'ion-wineglass', 'ion-woman', 'ion-wrench', 'ion-xbox'
            ];

            $nucleos = [
                "Flechas" => [
                    'arrows-1_cloud-download-93', 'arrows-1_cloud-upload-94', 'arrows-1_minimal-down',
                    'arrows-1_minimal-left', 'arrows-1_minimal-right', 'arrows-1_minimal-up',
                    'arrows-1_refresh-69', 'arrows-1_share-66'
                ],
                "Negocio" => [
                    "business_badge", "business_bank", "business_briefcase-24", "business_bulb-63",
                    "business_chart-bar-32", "business_chart-pie-36", "business_globe",
                    "business_money-coins"
                ],
                "Ropa y Accesorios" => [
                    "clothes_tie-bow"
                ],
                "Diseño y Desarrollo" => [
                    "design_vector", "design_app", "design_bullet-list-67", "design_image", "design_palette",
                    "design_scissors", "design-2_html5", "design-2_ruler-pencil"
                ],
                "Emoticones" => [
                    "emoticons_satisfied"
                ],
                "Archivos y Carpetas" => [
                    "files_box", "files_paper", "files_single-copy-04"
                ],
                "Salud y Medicina" => [
                    "health_ambulance"
                ],
                "Cargadores" => [
                    'loader_gear spin', 'loader_refresh spin'
                ],
                "Mapas y Localización" => [
                    'location_bookmark', 'location_compass-05', 'location_map-big', 'location_pin', 'location_world'
                ],
                "Media" => [
                    'media-1_album', 'media-1_button-pause', 'media-1_button-play', 'media-1_button-power',
                    'media-1_camera-compact', 'media-2_note-03', 'media-2_sound-wave'
                ],
                "Objetos" => [
                    'objects_diamond', 'objects_globe', 'objects_key-25', 'objects_planet', 'objects_spaceship',
                    'objects_support-17', 'objects_umbrella-13'
                ],
                "Escuela y Educación" => [
                    'education_agenda-bookmark', 'education_atom', 'education_glasses', 'education_hat',
                    'education_paper'
                ],
                "Compras" => [
                    'shopping_bag-16', 'shopping_basket', 'shopping_box', 'shopping_cart-simple',
                    'shopping_credit-card', 'shopping_delivery-fast', 'shopping_shop', 'shopping_tag-content'
                ],
                "Deporte" => [
                    'sport_trophy', 'sport_user-run'
                ],
                "Tecnología" => [
                    'tech_controller-modern', 'tech_headphones', 'tech_laptop', 'tech_mobile', 'tech_tablet',
                    'tech_tv', 'tech_watch-time'
                ],
                "Edición de texto" => [
                    'text_align-center', 'text_align-left', 'text_bold', 'text_caps-small'
                ],
                "Gestos táctiles" => [
                    'gestures_tap-01'
                ],
                "Transporte" => [
                    'transportation_air-baloon', 'transportation_bus-front-12'
                ],
                "Viaje" => [
                    'travel_info', 'travel_istanbul'
                ],
                "Interfaz de usuario" => [
                    "ui-1_check", "ui-1_email-85", 'ui-1_bell-53', 'ui-1_calendar-60', 'ui-1_lock-circle-open',
                    'ui-1_send', 'ui-1_settings-gear-63', 'ui-1_simple-add', 'ui-1_simple-delete',
                    'ui-1_simple-remove', 'ui-1_zoom-bold', 'ui-2_chat-round', 'ui-2_favourite-28', 'ui-2_like',
                    'ui-2_settings-90', 'ui-2_time-alarm'
                ],
                "Usuarios" => [
                    "users_circle-08", "users_single-02"
                ]
            ];
            $view['icons']['vars'] = compact('icofonts', 'fontawesomes', 'ionicons', 'nucleos');
        }

        return view("dev." . $view[$el]['view'], $view[$el]['vars']);
    }
}
