@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h6 class="card-title">Pack Icofont</h6>
					<div class="card-btns">
						@include('buttons.minimize')
					</div>
				</div>
				<div class="card-body">
					@php
						$icofonts = [
							'icofont-angry-monster', 'icofont-bathtub', 'icofont-bird-wings', 'icofont-bow', 
							'icofont-brain-alt', 'icofont-butterfly-alt', 'icofont-castle', 'icofont-circuit', 
							'icofont-dart', 'icofont-dice-alt', 'icofont-disability-race', 'icofont-diving-goggle', 
							'icofont-fire-alt', 'icofont-flame-torch', 'icofont-flora-flower', 'icofont-flora', 
							'icofont-gift-box', 'icofont-halloween-pumpkin', 'icofont-hand-power', 'icofont-hand-thunder', 
							'icofont-king-crown', 'icofont-king-monster', 'icofont-love', 'icofont-magician-hat', 
							'icofont-native-american', 'icofont-open-eye', 'icofont-owl-look', 'icofont-phoenix', 
							'icofont-queen-crown', 'icofont-robot-face', 'icofont-sand-clock', 'icofont-shield-alt', 
							'icofont-ship-wheel', 'icofont-skull-danger', 'icofont-skull-face', 'icofont-snail', 
							'icofont-snow-alt', 'icofont-snow-flake', 'icofont-snowmobile', 'icofont-space-shuttle', 
							'icofont-star-shape', 'icofont-swirl', 'icofont-tattoo-wing', 'icofont-throne', 'icofont-touch', 
							'icofont-tree-alt', 'icofont-triangle', 'icofont-unity-hand', 'icofont-weed', 'icofont-woman-bird', 
							'icofont-animal-bat', 'icofont-animal-bear-tracks', 'icofont-animal-bear', 'icofont-animal-bird-alt', 
							'icofont-animal-bird', 'icofont-animal-bone', 'icofont-animal-bull', 'icofont-animal-camel-alt', 
							'icofont-animal-camel-head', 'icofont-animal-camel', 'icofont-animal-cat-alt-1', 
							'icofont-animal-cat-alt-2', 'icofont-animal-cat-alt-3', 'icofont-animal-cat-alt-4', 
							'icofont-animal-cat-with-dog', 'icofont-animal-cat', 'icofont-animal-cow-head', 
							'icofont-animal-cow', 'icofont-animal-crab', 'icofont-animal-crocodile', 'icofont-animal-deer-head', 
							'icofont-animal-dog-alt', 'icofont-animal-dog-barking', 'icofont-animal-dog', 
							'icofont-animal-dolphin', 'icofont-animal-duck-tracks', 'icofont-animal-eagle-head', 
							'icofont-animal-eaten-fish', 'icofont-animal-elephant-alt', 'icofont-animal-elephant-head-alt', 
							'icofont-animal-elephant-head', 'icofont-animal-elephant', 'icofont-animal-elk', 
							'icofont-animal-fish-alt-1', 'icofont-animal-fish-alt-2', 'icofont-animal-fish-alt-3', 
							'icofont-animal-fish-alt-4', 'icofont-animal-fish', 'icofont-animal-fox-alt', 'icofont-animal-fox', 
							'icofont-animal-frog-tracks', 'icofont-animal-frog', 'icofont-animal-froggy', 
							'icofont-animal-giraffe-alt', 'icofont-animal-giraffe', 'icofont-animal-goat-head-alt-1', 
							'icofont-animal-goat-head-alt-2', 'icofont-animal-goat-head', 'icofont-animal-gorilla', 
							'icofont-animal-hen-tracks', 'icofont-animal-horse-head-alt-1', 'icofont-animal-horse-head-alt-2', 
							'icofont-animal-horse-head', 'icofont-animal-horse-tracks', 'icofont-animal-jellyfish', 
							'icofont-animal-kangaroo', 'icofont-animal-lemur', 'icofont-animal-lion-alt', 
							'icofont-animal-lion-head-alt', 'icofont-animal-lion-head', 'icofont-animal-lion', 
							'icofont-animal-monkey-alt-1', 'icofont-animal-monkey-alt-2', 'icofont-animal-monkey-alt-3', 
							'icofont-animal-monkey', 'icofont-animal-octopus-alt', 'icofont-animal-octopus', 
							'icofont-animal-owl', 'icofont-animal-panda-alt', 'icofont-animal-panda', 'icofont-animal-panther', 
							'icofont-animal-parrot-lip', 'icofont-animal-parrot', 'icofont-animal-paw', 
							'icofont-animal-pelican', 'icofont-animal-penguin', 'icofont-animal-pig-alt', 
							'icofont-animal-pig', 'icofont-animal-pigeon-alt', 'icofont-animal-pigeon', 
							'icofont-animal-pigeons', 'icofont-animal-rabbit-running', 'icofont-animal-rat-alt', 
							'icofont-animal-rhino-head', 'icofont-animal-rhino', 'icofont-animal-rooster', 
							'icofont-animal-seahorse', 'icofont-animal-seal', 'icofont-animal-shrimp', 
							'icofont-animal-snail-alt-1', 'icofont-animal-snail-alt-2', 'icofont-animal-snail', 
							'icofont-animal-snake', 'icofont-animal-squid', 'icofont-animal-squirrel', 
							'icofont-animal-tiger-alt', 'icofont-animal-tiger', 'icofont-animal-turtle', 
							'icofont-animal-whale', 'icofont-animal-woodpecker', 'icofont-animal-zebra', 
							'icofont-brand-acer', 'icofont-brand-adidas', 'icofont-brand-adobe', 'icofont-brand-air-new-zealand', 
							'icofont-brand-airbnb', 'icofont-brand-aircell', 'icofont-brand-airtel', 'icofont-brand-alcatel', 
							'icofont-brand-alibaba', 'icofont-brand-aliexpress', 'icofont-brand-alipay', 'icofont-brand-amazon', 
							'icofont-brand-amd', 'icofont-brand-american-airlines', 'icofont-brand-android-robot', 
							'icofont-brand-android', 'icofont-brand-aol', 'icofont-brand-apple', 'icofont-brand-appstore', 
							'icofont-brand-asus', 'icofont-brand-ati', 'icofont-brand-att', 'icofont-brand-audi', 
							'icofont-brand-axiata', 'icofont-brand-bada', 'icofont-brand-bbc', 'icofont-brand-bing', 
							'icofont-brand-blackberry', 'icofont-brand-bmw', 'icofont-brand-box', 'icofont-brand-burger-king', 
							'icofont-brand-business-insider', 'icofont-brand-buzzfeed', 'icofont-brand-cannon', 
							'icofont-brand-casio', 'icofont-brand-china-mobile', 'icofont-brand-china-telecom', 
							'icofont-brand-china-unicom', 'icofont-brand-cisco', 'icofont-brand-citibank', 'icofont-brand-cnet', 
							'icofont-brand-cnn', 'icofont-brand-cocal-cola', 'icofont-brand-compaq', 'icofont-brand-copy', 
							'icofont-brand-debian', 'icofont-brand-delicious', 'icofont-brand-dell', 'icofont-brand-designbump', 
							'icofont-brand-designfloat', 'icofont-brand-disney', 'icofont-brand-dodge', 'icofont-brand-dove', 
							'icofont-brand-ebay', 'icofont-brand-eleven', 'icofont-brand-emirates', 'icofont-brand-espn', 
							'icofont-brand-etihad-airways', 'icofont-brand-etisalat', 'icofont-brand-etsy', 
							'icofont-brand-facebook', 'icofont-brand-fastrack', 'icofont-brand-fedex', 'icofont-brand-ferrari', 
							'icofont-brand-fitbit', 'icofont-brand-flikr', 'icofont-brand-forbes', 'icofont-brand-foursquare', 
							'icofont-brand-fox', 'icofont-brand-foxconn', 'icofont-brand-fujitsu', 
							'icofont-brand-general-electric', 'icofont-brand-gillette', 'icofont-brand-gizmodo', 
							'icofont-brand-gnome', 'icofont-brand-google', 'icofont-brand-gopro', 'icofont-brand-gucci', 
							'icofont-brand-hallmark', 'icofont-brand-hi5', 'icofont-brand-honda', 'icofont-brand-hp', 
							'icofont-brand-hsbc', 'icofont-brand-htc', 'icofont-brand-huawei', 'icofont-brand-hulu', 
							'icofont-brand-hyundai', 'icofont-brand-ibm', 'icofont-brand-icofont', 'icofont-brand-icq', 
							'icofont-brand-ikea', 'icofont-brand-imdb', 'icofont-brand-indiegogo', 'icofont-brand-intel', 
							'icofont-brand-ipair', 'icofont-brand-jaguar', 'icofont-brand-java', 'icofont-brand-joomshaper', 
							'icofont-brand-kickstarter', 'icofont-brand-kik', 'icofont-brand-lastfm', 'icofont-brand-lego', 
							'icofont-brand-lenovo', 'icofont-brand-levis', 'icofont-brand-lexus', 'icofont-brand-lg', 
							'icofont-brand-life-hacker', 'icofont-brand-line-messenger', 'icofont-brand-linkedin', 
							'icofont-brand-linux-mint', 'icofont-brand-linux', 'icofont-brand-lionix', 
							'icofont-brand-live-messenger', 'icofont-brand-loreal', 'icofont-brand-louis-vuitton', 
							'icofont-brand-mac-os', 'icofont-brand-marvel-app', 'icofont-brand-mashable', 'icofont-brand-mazda', 
							'icofont-brand-mcdonals', 'icofont-brand-mercedes', 'icofont-brand-micromax', 
							'icofont-brand-microsoft', 'icofont-brand-mobileme', 'icofont-brand-mobily', 
							'icofont-brand-motorola', 'icofont-brand-msi', 'icofont-brand-mts', 'icofont-brand-myspace', 
							'icofont-brand-mytv', 'icofont-brand-nasa', 'icofont-brand-natgeo', 'icofont-brand-nbc', 
							'icofont-brand-nescafe', 'icofont-brand-nestle', 'icofont-brand-netflix', 'icofont-brand-nexus', 
							'icofont-brand-nike', 'icofont-brand-nokia', 'icofont-brand-nvidia', 'icofont-brand-omega', 
							'icofont-brand-opensuse', 'icofont-brand-oracle', 'icofont-brand-panasonic', 'icofont-brand-paypal', 
							'icofont-brand-pepsi', 'icofont-brand-philips', 'icofont-brand-pizza-hut', 
							'icofont-brand-playstation', 'icofont-brand-puma', 'icofont-brand-qatar-air', 'icofont-brand-qvc', 
							'icofont-brand-readernaut', 'icofont-brand-redbull', 'icofont-brand-reebok', 'icofont-brand-reuters', 
							'icofont-brand-samsung', 'icofont-brand-sap', 'icofont-brand-saudia-airlines', 
							'icofont-brand-scribd', 'icofont-brand-shell', 'icofont-brand-siemens', 'icofont-brand-sk-telecom', 
							'icofont-brand-slideshare', 'icofont-brand-smashing-magazine', 'icofont-brand-snapchat', 
							'icofont-brand-sony-ericsson', 'icofont-brand-sony', 'icofont-brand-soundcloud', 
							'icofont-brand-sprint', 'icofont-brand-squidoo', 'icofont-brand-starbucks', 'icofont-brand-stc', 
							'icofont-brand-steam', 'icofont-brand-suzuki', 'icofont-brand-symbian', 'icofont-brand-t-mobile', 
							'icofont-brand-tango', 'icofont-brand-target', 'icofont-brand-tata-indicom', 
							'icofont-brand-techcrunch', 'icofont-brand-telenor', 'icofont-brand-teliasonera', 
							'icofont-brand-tesla', 'icofont-brand-the-verge', 'icofont-brand-thenextweb', 
							'icofont-brand-toshiba', 'icofont-brand-toyota', 'icofont-brand-tribenet', 'icofont-brand-ubuntu', 
							'icofont-brand-unilever', 'icofont-brand-vaio', 'icofont-brand-verizon', 'icofont-brand-viber', 
							'icofont-brand-vodafone', 'icofont-brand-volkswagen', 'icofont-brand-walmart', 
							'icofont-brand-warnerbros', 'icofont-brand-whatsapp', 'icofont-brand-wikipedia', 
							'icofont-brand-windows', 'icofont-brand-wire', 'icofont-brand-yahoobuzz', 'icofont-brand-yamaha', 
							'icofont-brand-youtube', 'icofont-brand-zain', 'icofont-bank-alt', 'icofont-barcode', 
							'icofont-basket', 'icofont-bill-alt', 'icofont-billboard', 'icofont-briefcase-alt-1', 
							'icofont-briefcase-alt-2', 'icofont-building-alt', 'icofont-businessman', 'icofont-businesswoman', 
							'icofont-cart-alt', 'icofont-chair', 'icofont-clip', 'icofont-coins', 'icofont-company', 
							'icofont-contact-add', 'icofont-deal', 'icofont-files', 'icofont-growth', 'icofont-id-card', 
							'icofont-idea', 'icofont-list', 'icofont-meeting-add', 'icofont-money-bag', 'icofont-people', 
							'icofont-pie-chart', 'icofont-presentation-alt', 'icofont-stamp', 'icofont-stock-mobile', 
							'icofont-support', 'icofont-tasks-alt', 'icofont-wheel', 'icofont-chart-arrows-axis', 
							'icofont-chart-bar-graph', 'icofont-chart-flow-alt-1', 'icofont-chart-flow-alt-2', 
							'icofont-chart-flow', 'icofont-chart-histogram-alt', 'icofont-chart-histogram', 
							'icofont-chart-line-alt', 'icofont-chart-line', 'icofont-chart-pie-alt', 'icofont-chart-pie', 
							'icofont-chart-radar-graph', 'icofont-cur-afghani-false', 'icofont-cur-afghani-minus', 
							'icofont-cur-afghani-plus', 'icofont-cur-afghani-true', 'icofont-cur-afghani', 
							'icofont-cur-baht-false', 'icofont-cur-baht-minus', 'icofont-cur-baht-plus', 'icofont-cur-baht-true', 
							'icofont-cur-baht', 'icofont-cur-bitcoin-false', 'icofont-cur-bitcoin-minus', 
							'icofont-cur-bitcoin-plus', 'icofont-cur-bitcoin-true', 'icofont-cur-bitcoin', 
							'icofont-cur-dollar-flase', 'icofont-cur-dollar-minus', 'icofont-cur-dollar-plus', 
							'icofont-cur-dollar-true', 'icofont-cur-dollar', 'icofont-cur-dong-false', 'icofont-cur-dong-minus', 
							'icofont-cur-dong-plus', 'icofont-cur-dong-true', 'icofont-cur-dong', 'icofont-cur-euro-false', 
							'icofont-cur-euro-minus', 'icofont-cur-euro-plus', 'icofont-cur-euro-true', 'icofont-cur-euro', 
							'icofont-cur-frank-false', 'icofont-cur-frank-minus', 'icofont-cur-frank-plus', 
							'icofont-cur-frank-true', 'icofont-cur-frank', 'icofont-cur-hryvnia-false', 
							'icofont-cur-hryvnia-minus', 'icofont-cur-hryvnia-plus', 'icofont-cur-hryvnia-true', 
							'icofont-cur-hryvnia', 'icofont-cur-lira-false', 'icofont-cur-lira-minus', 'icofont-cur-lira-plus', 
							'icofont-cur-lira-true', 'icofont-cur-lira', 'icofont-cur-peseta-false', 'icofont-cur-peseta-minus', 
							'icofont-cur-peseta-plus', 'icofont-cur-peseta-true', 'icofont-cur-peseta', 'icofont-cur-peso-false', 
							'icofont-cur-peso-minus', 'icofont-cur-peso-plus', 'icofont-cur-peso-true', 'icofont-cur-peso', 
							'icofont-cur-pound-false', 'icofont-cur-pound-minus', 'icofont-cur-pound-plus', 
							'icofont-cur-pound-true', 'icofont-cur-pound', 'icofont-cur-renminbi-false', 
							'icofont-cur-renminbi-minus', 'icofont-cur-renminbi-plus', 'icofont-cur-renminbi-true', 
							'icofont-cur-renminbi', 'icofont-cur-riyal-false', 'icofont-cur-riyal-minus', 
							'icofont-cur-riyal-plus', 'icofont-cur-riyal-true', 'icofont-cur-riyal', 'icofont-cur-rouble-false', 
							'icofont-cur-rouble-minus', 'icofont-cur-rouble-plus', 'icofont-cur-rouble-true', 
							'icofont-cur-rouble', 'icofont-cur-rupee-false', 'icofont-cur-rupee-minus', 'icofont-cur-rupee-plus', 
							'icofont-cur-rupee-true', 'icofont-cur-rupee', 'icofont-cur-taka-false', 'icofont-cur-taka-minus', 
							'icofont-cur-taka-plus', 'icofont-cur-taka-true', 'icofont-cur-taka', 
							'icofont-cur-turkish-lira-false', 'icofont-cur-turkish-lira-minus', 'icofont-cur-turkish-lira-plus', 
							'icofont-cur-turkish-lira-true', 'icofont-cur-turkish-lira', 'icofont-cur-won-false', 
							'icofont-cur-won-minus', 'icofont-cur-won-plus', 'icofont-cur-won-true', 'icofont-cur-won', 
							'icofont-cur-yen-false', 'icofont-cur-yen-minus', 'icofont-cur-yen-plus', 'icofont-cur-yen-true', 
							'icofont-cur-yen', 'icofont-android-nexus', 'icofont-android-tablet', 'icofont-apple-watch', 
							'icofont-drwaing-tablet', 'icofont-earphone', 'icofont-flash-drive', 'icofont-game-control', 
							'icofont-headphone-alt', 'icofont-htc-one', 'icofont-imac', 'icofont-ipad-touch', 'icofont-iphone', 
							'icofont-ipod-nano', 'icofont-ipod-touch', 'icofont-keyboard-alt', 'icofont-keyboard-wireless', 
							'icofont-laptop-alt', 'icofont-macbook', 'icofont-magic-mouse', 'icofont-microphone-alt', 
							'icofont-monitor', 'icofont-mouse', 'icofont-nintendo', 'icofont-playstation', 'icofont-psvita', 
							'icofont-radio-mic', 'icofont-refrigerator', 'icofont-samsung-galaxy', 'icofont-surface-tablet', 
							'icofont-washing-machine', 'icofont-wifi-router', 'icofont-wii-u', 'icofont-windows-lumia', 
							'icofont-wireless-mouse', 'icofont-xbox-360', 'icofont-arrow-down', 'icofont-arrow-left', 
							'icofont-arrow-right', 'icofont-arrow-up', 'icofont-block-down', 'icofont-block-left', 
							'icofont-block-right', 'icofont-block-up', 'icofont-bubble-down', 'icofont-bubble-left', 
							'icofont-bubble-right', 'icofont-bubble-up', 'icofont-caret-down', 'icofont-caret-left', 
							'icofont-caret-right', 'icofont-caret-up', 'icofont-circled-down', 'icofont-circled-left', 
							'icofont-circled-right', 'icofont-circled-up', 'icofont-collapse', 'icofont-cursor-drag', 
							'icofont-curved-double-left', 'icofont-curved-double-right', 'icofont-curved-down', 
							'icofont-curved-left', 'icofont-curved-right', 'icofont-curved-up', 'icofont-dotted-down', 
							'icofont-dotted-left', 'icofont-dotted-right', 'icofont-dotted-up', 'icofont-double-left', 
							'icofont-double-right', 'icofont-drag', 'icofont-drag1', 'icofont-drag2', 'icofont-drag3', 
							'icofont-expand-alt', 'icofont-hand-down', 'icofont-hand-drag', 'icofont-hand-drag1', 
							'icofont-hand-drag2', 'icofont-hand-drawn-alt-down', 'icofont-hand-drawn-alt-left', 
							'icofont-hand-drawn-alt-right', 'icofont-hand-drawn-alt-up', 'icofont-hand-drawn-down', 
							'icofont-hand-drawn-left', 'icofont-hand-drawn-right', 'icofont-hand-drawn-up', 'icofont-hand-left', 
							'icofont-hand-right', 'icofont-hand-up', 'icofont-line-block-down', 'icofont-line-block-left', 
							'icofont-line-block-right', 'icofont-line-block-up', 'icofont-long-arrow-down', 
							'icofont-long-arrow-left', 'icofont-long-arrow-right', 'icofont-long-arrow-up', 
							'icofont-rounded-collapse', 'icofont-rounded-double-left', 'icofont-rounded-double-right', 
							'icofont-rounded-down', 'icofont-rounded-expand', 'icofont-rounded-left-down', 
							'icofont-rounded-left-up', 'icofont-rounded-left', 'icofont-rounded-right-down', 
							'icofont-rounded-right-up', 'icofont-rounded-right', 'icofont-rounded-up', 
							'icofont-scroll-bubble-down', 'icofont-scroll-bubble-left', 'icofont-scroll-bubble-right', 
							'icofont-scroll-bubble-up', 'icofont-scroll-double-down', 'icofont-scroll-double-left', 
							'icofont-scroll-double-right', 'icofont-scroll-double-up', 'icofont-scroll-down', 
							'icofont-scroll-left', 'icofont-scroll-long-down', 'icofont-scroll-long-left', 
							'icofont-scroll-long-right', 'icofont-scroll-long-up', 'icofont-scroll-right', 'icofont-scroll-up', 
							'icofont-simple-down', 'icofont-simple-left-down', 'icofont-simple-left-up', 'icofont-simple-left', 
							'icofont-simple-right-down', 'icofont-simple-right-up', 'icofont-simple-right', 'icofont-simple-up', 
							'icofont-square-down', 'icofont-square-left', 'icofont-square-right', 'icofont-square-up', 
							'icofont-stylish-down', 'icofont-stylish-left', 'icofont-stylish-right', 'icofont-stylish-up', 
							'icofont-swoosh-down', 'icofont-swoosh-left', 'icofont-swoosh-right', 'icofont-swoosh-up', 
							'icofont-thin-double-left', 'icofont-thin-double-right', 'icofont-thin-down', 'icofont-thin-left', 
							'icofont-thin-right', 'icofont-thin-up', 'icofont-atom', 'icofont-award', 'icofont-bell-alt', 
							'icofont-book-alt', 'icofont-brainstorming', 'icofont-certificate-alt-1', 
							'icofont-certificate-alt-2', 'icofont-dna-alt-2', 'icofont-education', 'icofont-electron', 
							'icofont-fountain-pen', 'icofont-globe-alt', 'icofont-graduate-alt', 'icofont-group-students', 
							'icofont-hat-alt', 'icofont-hat', 'icofont-instrument', 'icofont-lamp-light', 
							'icofont-microscope-alt', 'icofont-paper', 'icofont-pen-alt-4', 'icofont-pen-nib', 
							'icofont-pencil-alt-5', 'icofont-quill-pen', 'icofont-read-book-alt', 'icofont-read-book', 
							'icofont-school-bag', 'icofont-school-bus', 'icofont-student-alt', 'icofont-student', 
							'icofont-teacher', 'icofont-test-bulb', 'icofont-test-tube-alt', 'icofont-university', 
							'icofont-emo-angry', 'icofont-emo-astonished', 'icofont-emo-confounded', 'icofont-emo-confused', 
							'icofont-emo-crying', 'icofont-emo-dizzy', 'icofont-emo-expressionless', 'icofont-emo-heart-eyes', 
							'icofont-emo-laughing', 'icofont-emo-nerd-smile', 'icofont-emo-open-mouth', 'icofont-emo-rage', 
							'icofont-emo-rolling-eyes', 'icofont-emo-sad', 'icofont-emo-simple-smile', 
							'icofont-emo-slightly-smile', 'icofont-emo-smirk', 'icofont-emo-stuck-out-tongue', 
							'icofont-emo-wink-smile', 'icofont-emo-worried', 'icofont-architecture-alt', 'icofont-architecture', 
							'icofont-barricade', 'icofont-bricks', 'icofont-calculations', 'icofont-cement-mix', 
							'icofont-cement-mixer', 'icofont-danger-zone', 'icofont-drill', 'icofont-eco-energy', 
							'icofont-eco-environmen', 'icofont-energy-air', 'icofont-energy-oil', 'icofont-energy-savings', 
							'icofont-energy-solar', 'icofont-energy-water', 'icofont-engineer', 'icofont-fire-extinguisher-alt', 
							'icofont-fix-tools', 'icofont-glue-oil', 'icofont-hammer-alt', 'icofont-help-robot', 
							'icofont-industries-alt-1', 'icofont-industries-alt-2', 'icofont-industries-alt-3', 
							'icofont-industries-alt-4', 'icofont-industries-alt-5', 'icofont-industries', 'icofont-labour', 
							'icofont-mining', 'icofont-paint-brush', 'icofont-pollution', 'icofont-power-zone', 
							'icofont-radio-active', 'icofont-recycle-alt', 'icofont-recycling-man', 'icofont-safety-hat-light', 
							'icofont-safety-hat', 'icofont-saw', 'icofont-screw-driver', 'icofont-settings-alt', 
							'icofont-tools-alt-1', 'icofont-tools-alt-2', 'icofont-tools-bag', 'icofont-trolley', 
							'icofont-trowel', 'icofont-under-construction-alt', 'icofont-under-construction', 
							'icofont-vehicle-cement', 'icofont-vehicle-crane', 'icofont-vehicle-delivery-van', 
							'icofont-vehicle-dozer', 'icofont-vehicle-excavator', 'icofont-vehicle-trucktor', 
							'icofont-vehicle-wrecking', 'icofont-worker-group', 'icofont-worker', 'icofont-wrench', 
							'icofont-file-audio', 'icofont-file-avi-mp4', 'icofont-file-bmp', 'icofont-file-code', 
							'icofont-file-css', 'icofont-file-document', 'icofont-file-eps', 'icofont-file-excel', 
							'icofont-file-exe', 'icofont-file-file', 'icofont-file-flv', 'icofont-file-gif', 
							'icofont-file-html5', 'icofont-file-image', 'icofont-file-iso', 'icofont-file-java', 
							'icofont-file-javascript', 'icofont-file-jpg', 'icofont-file-midi', 'icofont-file-mov', 
							'icofont-file-mp3', 'icofont-file-pdf', 'icofont-file-php', 'icofont-file-png', 
							'icofont-file-powerpoint', 'icofont-file-presentation', 'icofont-file-psb', 'icofont-file-psd', 
							'icofont-file-python', 'icofont-file-ruby', 'icofont-file-spreadsheet', 'icofont-file-sql', 
							'icofont-file-svg', 'icofont-file-text', 'icofont-file-tiff', 'icofont-file-video', 
							'icofont-file-wave', 'icofont-file-wmv', 'icofont-file-word', 'icofont-file-zip', 'icofont-apple', 
							'icofont-arabian-coffee', 'icofont-artichoke', 'icofont-asparagus', 'icofont-avocado', 
							'icofont-baby-food', 'icofont-banana', 'icofont-bbq', 'icofont-beans', 'icofont-beer', 
							'icofont-bell-pepper-capsicum', 'icofont-birthday-cake', 'icofont-bread', 'icofont-broccoli', 
							'icofont-burger', 'icofont-cabbage', 'icofont-carrot', 'icofont-cauli-flower', 'icofont-cheese', 
							'icofont-chef', 'icofont-cherry', 'icofont-chicken-fry', 'icofont-chicken', 'icofont-cocktail', 
							'icofont-coconut', 'icofont-coffee-alt', 'icofont-coffee-mug', 'icofont-coffee-pot', 'icofont-cola', 
							'icofont-corn', 'icofont-croissant', 'icofont-crop-plant', 'icofont-cucumber', 'icofont-cup-cake', 
							'icofont-dining-table', 'icofont-donut', 'icofont-egg-plant', 'icofont-egg-poached', 
							'icofont-farmer', 'icofont-farmer1', 'icofont-fast-food', 'icofont-fish', 'icofont-food-basket', 
							'icofont-food-cart', 'icofont-fork-and-knife', 'icofont-french-fries', 'icofont-fresh-juice', 
							'icofont-fruits', 'icofont-grapes', 'icofont-honey', 'icofont-hot-dog', 'icofont-hotel-alt', 
							'icofont-ice-cream-alt', 'icofont-ice-cream', 'icofont-ketchup', 'icofont-kiwi', 
							'icofont-layered-cake', 'icofont-lemon-alt', 'icofont-lobster', 'icofont-mango', 'icofont-milk', 
							'icofont-mushroom', 'icofont-noodles', 'icofont-onion', 'icofont-orange', 'icofont-pear', 
							'icofont-peas', 'icofont-pepper', 'icofont-pie-alt', 'icofont-pineapple', 'icofont-pizza-slice', 
							'icofont-pizza', 'icofont-plant', 'icofont-popcorn', 'icofont-potato', 'icofont-pumpkin', 
							'icofont-raddish', 'icofont-restaurant-menu', 'icofont-restaurant', 'icofont-salt-and-pepper', 
							'icofont-sandwich', 'icofont-sausage', 'icofont-shrimp', 'icofont-sof-drinks', 'icofont-soup-bowl', 
							'icofont-spoon-and-fork', 'icofont-steak', 'icofont-strawberry', 'icofont-sub-sandwich', 
							'icofont-sushi', 'icofont-taco', 'icofont-tea-pot', 'icofont-tea', 'icofont-tomato', 
							'icofont-waiter-alt', 'icofont-watermelon', 'icofont-wheat', 'icofont-abc', 'icofont-baby-cloth', 
							'icofont-baby-milk-bottle', 'icofont-baby-trolley', 'icofont-back-pack', 'icofont-candy', 
							'icofont-cycling', 'icofont-holding-hands', 'icofont-infant-nipple', 'icofont-kids-scooter', 
							'icofont-safety-pin', 'icofont-teddy-bear', 'icofont-toy-ball', 'icofont-toy-cat', 
							'icofont-toy-duck', 'icofont-toy-elephant', 'icofont-toy-hand', 'icofont-toy-horse', 
							'icofont-toy-lattu', 'icofont-toy-train', 'icofont-unique-idea', 'icofont-bag-alt', 
							'icofont-burglar', 'icofont-cannon-firing', 'icofont-cc-camera', 'icofont-cop-badge', 'icofont-cop', 
							'icofont-court-hammer', 'icofont-court', 'icofont-finger-print', 'icofont-handcuff-alt', 
							'icofont-handcuff', 'icofont-investigation', 'icofont-investigator', 'icofont-jail', 
							'icofont-judge', 'icofont-law-alt-1', 'icofont-law-alt-2', 'icofont-law-alt-3', 'icofont-law-book', 
							'icofont-law-document', 'icofont-law', 'icofont-lawyer-alt-1', 'icofont-lawyer-alt-2', 
							'icofont-lawyer', 'icofont-order', 'icofont-pistol', 'icofont-police-badge', 'icofont-police-cap', 
							'icofont-police-car-alt-1', 'icofont-police-car-alt-2', 'icofont-police-hat', 'icofont-police-van', 
							'icofont-police', 'icofont-protect', 'icofont-scales', 'icofont-thief-alt', 'icofont-thief', 
							'icofont-abacus-alt', 'icofont-abacus', 'icofont-angle', 'icofont-calculator-alt-1', 
							'icofont-calculator-alt-2', 'icofont-circle-ruler-alt', 'icofont-circle-ruler', 
							'icofont-compass-alt-1', 'icofont-compass-alt-2', 'icofont-compass-alt-3', 'icofont-compass-alt-4', 
							'icofont-degrees-alt-1', 'icofont-degrees-alt-2', 'icofont-degrees', 'icofont-golden-ratio', 
							'icofont-marker-alt-1', 'icofont-marker-alt-2', 'icofont-marker-alt-3', 'icofont-mathematical-alt-1', 
							'icofont-mathematical-alt-2', 'icofont-mathematical', 'icofont-pen-alt-1', 'icofont-pen-alt-2', 
							'icofont-pen-alt-3', 'icofont-pen-holder-alt-1', 'icofont-pen-holder', 'icofont-pencil-alt-1', 
							'icofont-pencil-alt-2', 'icofont-pencil-alt-3', 'icofont-pencil-alt-4', 'icofont-ruler-alt-1', 
							'icofont-ruler-alt-2', 'icofont-ruler-compass-alt', 'icofont-ruler-compass', 
							'icofont-ruler-pencil-alt-1', 'icofont-ruler-pencil-alt-2', 'icofont-ruler-pencil', 'icofont-ruler', 
							'icofont-rulers-alt', 'icofont-rulers', 'icofont-square-root', 'icofont-aids', 'icofont-ambulance', 
							'icofont-autism', 'icofont-bandage', 'icofont-bed-patient', 'icofont-blind', 'icofont-blood-drop', 
							'icofont-blood-test', 'icofont-blood', 'icofont-capsule', 'icofont-crutches', 'icofont-dna-alt-1', 
							'icofont-dna', 'icofont-doctor-alt', 'icofont-doctor', 'icofont-drug-pack', 'icofont-drug', 
							'icofont-eye-alt', 'icofont-first-aid-alt', 'icofont-garbage', 'icofont-heart-alt', 
							'icofont-heartbeat', 'icofont-herbal', 'icofont-hospital', 'icofont-icu', 
							'icofont-injection-syringe', 'icofont-laboratory', 'icofont-medical-sign-alt', 
							'icofont-medical-sign', 'icofont-nurse-alt', 'icofont-nurse', 'icofont-nursing-home', 
							'icofont-operation-theater', 'icofont-paralysis-disability', 'icofont-pills', 'icofont-prescription', 
							'icofont-pulse', 'icofont-stethoscope-alt', 'icofont-stethoscope', 'icofont-stretcher', 
							'icofont-surgeon-alt', 'icofont-surgeon', 'icofont-tablets', 'icofont-test-bottle', 
							'icofont-test-tube', 'icofont-thermometer-alt', 'icofont-tooth', 'icofont-xray', 'icofont-ui-add', 
							'icofont-ui-alarm', 'icofont-ui-battery', 'icofont-ui-block', 'icofont-ui-bluetooth', 
							'icofont-ui-brightness', 'icofont-ui-browser', 'icofont-ui-calculator', 'icofont-ui-calendar', 
							'icofont-ui-call', 'icofont-ui-camera', 'icofont-ui-cart', 'icofont-ui-cell-phone', 
							'icofont-ui-chat', 'icofont-ui-check', 'icofont-ui-clip-board', 'icofont-ui-clip', 
							'icofont-ui-clock', 'icofont-ui-close', 'icofont-ui-contact-list', 'icofont-ui-copy', 
							'icofont-ui-cut', 'icofont-ui-delete', 'icofont-ui-dial-phone', 'icofont-ui-edit', 
							'icofont-ui-email', 'icofont-ui-file', 'icofont-ui-fire-wall', 'icofont-ui-flash-light', 
							'icofont-ui-flight', 'icofont-ui-folder', 'icofont-ui-game', 'icofont-ui-handicapped', 
							'icofont-ui-head-phone', 'icofont-ui-home', 'icofont-ui-image', 'icofont-ui-keyboard', 
							'icofont-ui-laoding', 'icofont-ui-lock', 'icofont-ui-love-add', 'icofont-ui-love-broken', 
							'icofont-ui-love-remove', 'icofont-ui-love', 'icofont-ui-map', 'icofont-ui-message', 
							'icofont-ui-messaging', 'icofont-ui-movie', 'icofont-ui-music-player', 'icofont-ui-music', 
							'icofont-ui-mute', 'icofont-ui-network', 'icofont-ui-next', 'icofont-ui-note', 'icofont-ui-office', 
							'icofont-ui-password', 'icofont-ui-pause', 'icofont-ui-play-stop', 'icofont-ui-play', 
							'icofont-ui-pointer', 'icofont-ui-power', 'icofont-ui-press', 'icofont-ui-previous', 
							'icofont-ui-rate-add', 'icofont-ui-rate-blank', 'icofont-ui-rate-remove', 'icofont-ui-rating', 
							'icofont-ui-record', 'icofont-ui-remove', 'icofont-ui-reply', 'icofont-ui-rotation', 
							'icofont-ui-rss', 'icofont-ui-search', 'icofont-ui-settings', 'icofont-ui-social-link', 
							'icofont-ui-tag', 'icofont-ui-text-chat', 'icofont-ui-text-loading', 'icofont-ui-theme', 
							'icofont-ui-timer', 'icofont-ui-touch-phone', 'icofont-ui-travel', 'icofont-ui-unlock', 
							'icofont-ui-user-group', 'icofont-ui-user', 'icofont-ui-v-card', 'icofont-ui-video-chat', 
							'icofont-ui-video-message', 'icofont-ui-video-play', 'icofont-ui-video', 'icofont-ui-volume', 
							'icofont-ui-weather', 'icofont-ui-wifi', 'icofont-ui-zoom-in', 'icofont-ui-zoom-out', 
							'icofont-cassette-player', 'icofont-cassette', 'icofont-forward', 'icofont-game', 'icofont-guiter', 
							'icofont-headphone-alt-1', 'icofont-headphone-alt-2', 'icofont-headphone-alt-3', 'icofont-listening', 
							'icofont-megaphone-alt', 'icofont-megaphone', 'icofont-movie', 'icofont-mp3-player', 
							'icofont-multimedia', 'icofont-music-disk', 'icofont-music-note', 'icofont-pause', 
							'icofont-play-alt-1', 'icofont-play-alt-2', 'icofont-play-alt-3', 'icofont-play-pause', 
							'icofont-record', 'icofont-retro-music-disk', 'icofont-rewind', 'icofont-song-notes', 
							'icofont-sound-wave-alt', 'icofont-sound-wave', 'icofont-stop', 'icofont-video-alt', 
							'icofont-video-cam', 'icofont-volume-bar', 'icofont-volume-mute', 'icofont-youtube-play', 
							'icofont-amazon-alt', 'icofont-amazon', 'icofont-american-express-alt', 'icofont-american-express', 
							'icofont-apple-pay-alt', 'icofont-apple-pay', 'icofont-bank-transfer-alt', 'icofont-bank-transfer', 
							'icofont-braintree-alt', 'icofont-braintree', 'icofont-cash-on-delivery-alt', 
							'icofont-cash-on-delivery', 'icofont-checkout-alt', 'icofont-checkout', 'icofont-diners-club-alt-1', 
							'icofont-diners-club-alt-2', 'icofont-diners-club-alt-3', 'icofont-diners-club', 
							'icofont-discover-alt', 'icofont-discover', 'icofont-eway-alt', 'icofont-eway', 
							'icofont-google-wallet-alt-1', 'icofont-google-wallet-alt-2', 'icofont-google-wallet-alt-3', 
							'icofont-google-wallet', 'icofont-jcb-alt', 'icofont-jcb', 'icofont-maestro-alt', 'icofont-maestro', 
							'icofont-mastercard-alt', 'icofont-mastercard', 'icofont-payoneer-alt', 'icofont-payoneer', 
							'icofont-paypal-alt', 'icofont-paypal', 'icofont-sage-alt', 'icofont-sage', 'icofont-skrill-alt', 
							'icofont-skrill', 'icofont-stripe-alt', 'icofont-stripe', 'icofont-visa-alt', 
							'icofont-visa-electron', 'icofont-visa', 'icofont-western-union-alt', 'icofont-western-union', 
							'icofont-boy', 'icofont-business-man-alt-1', 'icofont-business-man-alt-2', 
							'icofont-business-man-alt-3', 'icofont-business-man', 'icofont-funky-man', 'icofont-girl-alt', 
							'icofont-girl', 'icofont-hotel-boy-alt', 'icofont-hotel-boy', 'icofont-man-in-glasses', 
							'icofont-user-alt-1', 'icofont-user-alt-2', 'icofont-user-alt-3', 'icofont-user-alt-4', 
							'icofont-user-alt-5', 'icofont-user-alt-6', 'icofont-user-alt-7', 'icofont-user-female', 
							'icofont-user-male', 'icofont-user-suited', 'icofont-user', 'icofont-users-alt-1', 
							'icofont-users-alt-2', 'icofont-users-alt-3', 'icofont-users-alt-4', 'icofont-users-alt-5', 
							'icofont-users-alt-6', 'icofont-users-social', 'icofont-users', 'icofont-waiter', 
							'icofont-woman-in-glasses', 'icofont-document-search', 'icofont-folder-search', 
							'icofont-home-search', 'icofont-job-search', 'icofont-map-search', 'icofont-restaurant-search', 
							'icofont-search-alt-1', 'icofont-search-alt-2', 'icofont-search', 'icofont-stock-search', 
							'icofont-user-search', 'icofont-social-aim', 'icofont-social-badoo', 'icofont-social-bebo', 
							'icofont-social-behance', 'icofont-social-blogger', 'icofont-social-bootstrap', 
							'icofont-social-brightkite', 'icofont-social-cloudapp', 'icofont-social-concrete5', 
							'icofont-social-designbump', 'icofont-social-designfloat', 'icofont-social-deviantart', 
							'icofont-social-digg', 'icofont-social-dotcms', 'icofont-social-dribble', 'icofont-social-dropbox', 
							'icofont-brand-drupal', 'icofont-social-ebuddy', 'icofont-social-ello', 'icofont-social-ember', 
							'icofont-social-envato', 'icofont-social-evernote', 'icofont-social-facebook', 
							'icofont-social-feedburner', 'icofont-social-folkd', 'icofont-social-friendfeed', 
							'icofont-social-ghost', 'icofont-social-github', 'icofont-social-gnome', 
							'icofont-social-google-buzz', 'icofont-social-google-map', 'icofont-social-google-plus', 
							'icofont-social-google-talk', 'icofont-social-hype-machine', 'icofont-social-instagram', 
							'icofont-brand-joomla', 'icofont-social-kickstarter', 'icofont-social-line', 
							'icofont-social-linux-mint', 'icofont-social-livejournal', 'icofont-social-magento', 
							'icofont-social-meetup', 'icofont-social-mixx', 'icofont-social-newsvine', 'icofont-social-nimbuss', 
							'icofont-social-opencart', 'icofont-social-oscommerce', 'icofont-social-pandora', 
							'icofont-social-picasa', 'icofont-social-pinterest', 'icofont-social-prestashop', 
							'icofont-social-qik', 'icofont-social-readernaut', 'icofont-social-reddit', 'icofont-social-rss', 
							'icofont-social-shopify', 'icofont-social-silverstripe', 'icofont-social-skype', 
							'icofont-social-slashdot', 'icofont-social-smugmug', 'icofont-social-steam', 
							'icofont-social-stumbleupon', 'icofont-social-technorati', 'icofont-social-telegram', 
							'icofont-social-tinder', 'icofont-social-tumblr', 'icofont-social-twitter', 'icofont-social-typo3', 
							'icofont-social-ubercart', 'icofont-social-viber', 'icofont-social-viddler', 'icofont-social-vimeo', 
							'icofont-social-vine', 'icofont-social-virb', 'icofont-social-virtuemart', 'icofont-social-wechat', 
							'icofont-brand-wordpress', 'icofont-social-xing', 'icofont-social-yahoo', 'icofont-social-yelp', 
							'icofont-social-zencart', 'icofont-badminton-birdie', 'icofont-baseball', 'icofont-baseballer', 
							'icofont-basketball-hoop', 'icofont-basketball', 'icofont-billiard-ball', 'icofont-boot-alt-1', 
							'icofont-boot-alt-2', 'icofont-bowling-alt', 'icofont-bowling', 'icofont-canoe', 
							'icofont-cheer-leader', 'icofont-climbing', 'icofont-corner', 'icofont-cyclist', 
							'icofont-dumbbell-alt', 'icofont-dumbbell', 'icofont-field-alt', 'icofont-field', 
							'icofont-football-alt', 'icofont-foul', 'icofont-goal-keeper', 'icofont-goal', 'icofont-golf-alt', 
							'icofont-golf-bag', 'icofont-golf-field', 'icofont-golf', 'icofont-golfer', 'icofont-gym-alt-1', 
							'icofont-gym-alt-2', 'icofont-gym-alt-3', 'icofont-gym', 'icofont-hand-grippers', 
							'icofont-heart-beat-alt', 'icofont-helmet', 'icofont-hockey-alt', 'icofont-hockey', 
							'icofont-ice-skate', 'icofont-jersey-alt', 'icofont-jersey', 'icofont-jumping', 'icofont-kick', 
							'icofont-leg', 'icofont-match-review', 'icofont-medal-alt', 'icofont-muscle-alt', 'icofont-muscle', 
							'icofont-offside', 'icofont-olympic-logo', 'icofont-olympic', 'icofont-padding', 
							'icofont-penalty-card', 'icofont-racer', 'icofont-racing-car', 'icofont-racing-flag-alt', 
							'icofont-racing-flag', 'icofont-racings-wheel', 'icofont-referee', 'icofont-refree-jersey', 
							'icofont-result', 'icofont-rugby-ball', 'icofont-rugby-player', 'icofont-rugby', 
							'icofont-runner-alt-1', 'icofont-runner-alt-2', 'icofont-runner', 'icofont-score-board', 
							'icofont-skiing-man', 'icofont-skydiving-goggles', 'icofont-snow-mobile', 'icofont-steering', 
							'icofont-substitute', 'icofont-swimmer', 'icofont-table-tennis', 'icofont-team-alt', 'icofont-team', 
							'icofont-tennis-player', 'icofont-tennis', 'icofont-time', 'icofont-track', 'icofont-tracking', 
							'icofont-trophy-alt', 'icofont-trophy', 'icofont-volleyball-alt', 'icofont-volleyball-fire', 
							'icofont-volleyball', 'icofont-water-bottle', 'icofont-whisle', 'icofont-win-trophy', 
							'icofont-align-center', 'icofont-align-left', 'icofont-align-right', 'icofont-all-caps', 
							'icofont-bold', 'icofont-brush', 'icofont-clip-board', 'icofont-code-alt', 'icofont-color-bucket', 
							'icofont-color-picker', 'icofont-copy-alt', 'icofont-copy-black', 'icofont-cut', 
							'icofont-delete-alt', 'icofont-edit-alt', 'icofont-eraser-alt', 'icofont-file-alt', 'icofont-font', 
							'icofont-header', 'icofont-indent', 'icofont-italic-alt', 'icofont-justify-all', 
							'icofont-justify-center', 'icofont-justify-left', 'icofont-justify-right', 'icofont-line-height', 
							'icofont-link-alt', 'icofont-listine-dots', 'icofont-listing-box', 'icofont-listing-number', 
							'icofont-marker', 'icofont-outdent', 'icofont-paper-clip', 'icofont-paragraph', 'icofont-pin', 
							'icofont-printer', 'icofont-redo', 'icofont-rotation', 'icofont-save', 'icofont-small-cap', 
							'icofont-strike-through', 'icofont-sub-listing', 'icofont-subscript', 'icofont-superscript', 
							'icofont-table', 'icofont-text-height', 'icofont-text-width', 'icofont-trash', 'icofont-underline', 
							'icofont-undo', 'icofont-unlink', 'icofont-air-balloon', 'icofont-airplane-alt', 'icofont-airplane', 
							'icofont-ambulance-crescent', 'icofont-ambulance-cross', 'icofont-articulated-truck', 
							'icofont-auto-rickshaw', 'icofont-bicycle-alt-1', 'icofont-bicycle-alt-2', 'icofont-bull-dozer', 
							'icofont-bus-alt-1', 'icofont-bus-alt-2', 'icofont-bus-alt-3', 'icofont-cable-car', 
							'icofont-car-alt-1', 'icofont-car-alt-2', 'icofont-car-alt-3', 'icofont-car-alt-4', 
							'icofont-concrete-mixer', 'icofont-delivery-time', 'icofont-excavator', 'icofont-fast-delivery', 
							'icofont-fire-truck-alt', 'icofont-fire-truck', 'icofont-fork-lift', 'icofont-free-delivery', 
							'icofont-golf-cart', 'icofont-helicopter', 'icofont-motor-bike-alt', 'icofont-motor-bike', 
							'icofont-motor-biker', 'icofont-oil-truck', 'icofont-police-car', 'icofont-rickshaw', 
							'icofont-rocket-alt-1', 'icofont-rocket-alt-2', 'icofont-sail-boat', 'icofont-scooter', 
							'icofont-sea-plane', 'icofont-ship-alt', 'icofont-speed-boat', 'icofont-taxi', 'icofont-tow-truck', 
							'icofont-tractor', 'icofont-traffic-light', 'icofont-train-line', 'icofont-train-steam', 
							'icofont-tram', 'icofont-truck-alt', 'icofont-truck-loaded', 'icofont-truck', 'icofont-van-alt', 
							'icofont-van', 'icofont-yacht', 'icofont-5-star-hotel', 'icofont-anchor-alt', 'icofont-beach-bed', 
							'icofont-camping-vest', 'icofont-coconut-alt', 'icofont-direction-sign', 'icofont-hill-side', 
							'icofont-island-alt', 'icofont-long-drive', 'icofont-map-pins', 'icofont-plane-ticket', 
							'icofont-sail-boat-alt-1', 'icofont-sail-boat-alt-2', 'icofont-sandals-female', 
							'icofont-sandals-male', 'icofont-travelling', 'icofont-breakdown', 'icofont-celsius', 
							'icofont-clouds', 'icofont-cloudy', 'icofont-compass-alt', 'icofont-dust', 'icofont-eclipse', 
							'icofont-fahrenheit', 'icofont-forest-fire', 'icofont-full-night', 'icofont-full-sunny', 
							'icofont-hail-night', 'icofont-hail-rainy-night', 'icofont-hail-rainy-sunny', 'icofont-hail-rainy', 
							'icofont-hail-sunny', 'icofont-hail-thunder-night', 'icofont-hail-thunder-sunny', 
							'icofont-hail-thunder', 'icofont-hail', 'icofont-hill-night', 'icofont-hill-sunny', 'icofont-hill', 
							'icofont-hurricane', 'icofont-island', 'icofont-meteor', 'icofont-night', 'icofont-rainy-night', 
							'icofont-rainy-sunny', 'icofont-rainy-thunder', 'icofont-rainy', 'icofont-showy-night-hail', 
							'icofont-snow-temp', 'icofont-snow', 'icofont-snowy-hail', 'icofont-snowy-night-rainy', 
							'icofont-snowy-night', 'icofont-snowy-rainy', 'icofont-snowy-sunny-hail', 
							'icofont-snowy-sunny-rainy', 'icofont-snowy-sunny', 'icofont-snowy-thunder-night', 
							'icofont-snowy-thunder-sunny', 'icofont-snowy-thunder', 'icofont-snowy-windy-night', 
							'icofont-snowy-windy-sunny', 'icofont-snowy-windy', 'icofont-snowy', 'icofont-sun-alt', 
							'icofont-sun-rise', 'icofont-sun-set', 'icofont-sunny-day-temp', 'icofont-sunny', 
							'icofont-thermometer', 'icofont-thinder-light', 'icofont-tornado', 'icofont-umbrella-alt', 
							'icofont-volcano', 'icofont-wave', 'icofont-wind-scale-0', 'icofont-wind-scale-1', 
							'icofont-wind-scale-2', 'icofont-wind-scale-3', 'icofont-wind-scale-4', 'icofont-wind-scale-5', 
							'icofont-wind-scale-6', 'icofont-wind-scale-7', 'icofont-wind-scale-8', 'icofont-wind-scale-9', 
							'icofont-wind-scale-10', 'icofont-wind-scale-11', 'icofont-wind-scale-12', 'icofont-wind-waves', 
							'icofont-wind', 'icofont-windy-hail', 'icofont-windy-night', 'icofont-windy-raining', 
							'icofont-windy-sunny', 'icofont-windy-thunder-raining', 'icofont-windy-thunder', 'icofont-windy', 
							'icofont-addons', 'icofont-address-book', 'icofont-adjust', 'icofont-alarm', 'icofont-anchor', 
							'icofont-archive', 'icofont-at', 'icofont-attachment', 'icofont-audio', 'icofont-auto-mobile', 
							'icofont-automation', 'icofont-baby', 'icofont-badge', 'icofont-bag', 'icofont-ban', 
							'icofont-bank', 'icofont-bar-code', 'icofont-bars', 'icofont-battery-empty', 'icofont-battery-full', 
							'icofont-battery-half', 'icofont-battery-low', 'icofont-beach', 'icofont-beaker', 'icofont-bear', 
							'icofont-beard', 'icofont-bed', 'icofont-bell', 'icofont-beverage', 'icofont-bicycle', 
							'icofont-bill', 'icofont-bin', 'icofont-binary', 'icofont-binoculars', 'icofont-bird', 
							'icofont-birds', 'icofont-black-board', 'icofont-bluetooth', 'icofont-bolt', 'icofont-bomb', 
							'icofont-book-mark', 'icofont-book', 'icofont-boot', 'icofont-box', 'icofont-brain', 
							'icofont-briefcase', 'icofont-broken', 'icofont-bucket', 'icofont-bucket1', 'icofont-bucket2', 
							'icofont-bug', 'icofont-building', 'icofont-bullet', 'icofont-bullhorn', 'icofont-bullseye', 
							'icofont-bus', 'icofont-butterfly', 'icofont-cab', 'icofont-calculator', 'icofont-calendar', 
							'icofont-camera-alt', 'icofont-camera', 'icofont-car', 'icofont-card', 'icofont-cart', 
							'icofont-cc', 'icofont-certificate', 'icofont-charging', 'icofont-chat', 'icofont-check-alt', 
							'icofont-check-circled', 'icofont-check', 'icofont-checked', 'icofont-children-care', 
							'icofont-clock-time', 'icofont-close-circled', 'icofont-close-line-circled', 
							'icofont-close-line-squared-alt', 'icofont-close-line-squared', 'icofont-close-line', 
							'icofont-close-squared-alt', 'icofont-close-squared', 'icofont-close', 'icofont-cloud-download', 
							'icofont-cloud-refresh', 'icofont-cloud-upload', 'icofont-cloud', 'icofont-code-not-allowed', 
							'icofont-code', 'icofont-coffee-cup', 'icofont-comment', 'icofont-compass', 'icofont-computer', 
							'icofont-connection', 'icofont-console', 'icofont-contacts', 'icofont-contrast', 'icofont-copy', 
							'icofont-copyright', 'icofont-credit-card', 'icofont-crop', 'icofont-crown', 'icofont-cube', 
							'icofont-cubes', 'icofont-culinary', 'icofont-dashboard-web', 'icofont-dashboard', 'icofont-data', 
							'icofont-database-add', 'icofont-database-locked', 'icofont-database-remove', 'icofont-database', 
							'icofont-delete', 'icofont-diamond', 'icofont-dice', 'icofont-disabled', 'icofont-disc', 
							'icofont-diskette', 'icofont-document-folder', 'icofont-download-alt', 'icofont-download', 
							'icofont-downloaded', 'icofont-earth', 'icofont-ebook', 'icofont-edit', 'icofont-eject', 
							'icofont-email', 'icofont-envelope-open', 'icofont-envelope', 'icofont-eraser', 'icofont-error', 
							'icofont-exchange', 'icofont-exclamation-circle', 'icofont-exclamation-square', 
							'icofont-exclamation-tringle', 'icofont-exclamation', 'icofont-exit', 'icofont-expand', 
							'icofont-external-link', 'icofont-external', 'icofont-eye-blocked', 'icofont-eye-dropper', 
							'icofont-eye', 'icofont-favourite', 'icofont-fax', 'icofont-female', 'icofont-file', 
							'icofont-film', 'icofont-filter', 'icofont-fire-burn', 'icofont-fire-extinguisher', 'icofont-fire', 
							'icofont-first-aid', 'icofont-flag-alt-1', 'icofont-flag-alt-2', 'icofont-flag', 
							'icofont-flash-light', 'icofont-flash', 'icofont-flask', 'icofont-focus', 'icofont-folder-open', 
							'icofont-folder', 'icofont-foot-print', 'icofont-football-american', 'icofont-football', 
							'icofont-game-console', 'icofont-game-pad', 'icofont-gavel', 'icofont-gear', 'icofont-gears', 
							'icofont-gift', 'icofont-glass', 'icofont-globe', 'icofont-graduate', 'icofont-graffiti', 
							'icofont-grocery', 'icofont-group', 'icofont-hammer', 'icofont-hand', 'icofont-hanger', 
							'icofont-hard-disk', 'icofont-headphone', 'icofont-heart-beat', 'icofont-heart', 'icofont-history', 
							'icofont-home', 'icofont-horn', 'icofont-hotel', 'icofont-hour-glass', 'icofont-id', 
							'icofont-image', 'icofont-inbox', 'icofont-infinite', 'icofont-info-circle', 'icofont-info-square', 
							'icofont-info', 'icofont-institution', 'icofont-interface', 'icofont-invisible', 'icofont-italic', 
							'icofont-jacket', 'icofont-jar', 'icofont-jewlery', 'icofont-karate', 'icofont-key-hole', 
							'icofont-key', 'icofont-keyboard', 'icofont-kid', 'icofont-label', 'icofont-lamp', 
							'icofont-laptop', 'icofont-layers', 'icofont-layout', 'icofont-leaf', 'icofont-leaflet', 
							'icofont-learn', 'icofont-legal', 'icofont-lego', 'icofont-lemon', 'icofont-lens', 
							'icofont-letter', 'icofont-letterbox', 'icofont-library', 'icofont-license', 'icofont-life-bouy', 
							'icofont-life-buoy', 'icofont-life-jacket', 'icofont-life-ring', 'icofont-light-bulb', 
							'icofont-lighter', 'icofont-lightning-ray', 'icofont-like', 'icofont-link', 'icofont-live-support', 
							'icofont-location-arrow', 'icofont-location-pin', 'icofont-lock', 'icofont-login', 'icofont-logout', 
							'icofont-lollipop', 'icofont-look', 'icofont-loop', 'icofont-luggage', 'icofont-lunch', 
							'icofont-lungs', 'icofont-magic-alt', 'icofont-magic', 'icofont-magnet', 'icofont-mail-box', 
							'icofont-mail', 'icofont-male', 'icofont-map', 'icofont-math', 'icofont-maximize', 
							'icofont-measure', 'icofont-medal', 'icofont-medical', 'icofont-medicine', 'icofont-mega-phone', 
							'icofont-memorial', 'icofont-memory-card', 'icofont-mic-mute', 'icofont-mic', 'icofont-micro-chip', 
							'icofont-microphone', 'icofont-microscope', 'icofont-military', 'icofont-mill', 
							'icofont-minus-circle', 'icofont-minus-square', 'icofont-minus', 'icofont-mobile-phone', 
							'icofont-molecule', 'icofont-money', 'icofont-moon', 'icofont-mop', 'icofont-muffin', 
							'icofont-music-alt', 'icofont-music-notes', 'icofont-music', 'icofont-mustache', 
							'icofont-mute-volume', 'icofont-navigation-menu', 'icofont-navigation', 'icofont-network-tower', 
							'icofont-network', 'icofont-news', 'icofont-newspaper', 'icofont-no-smoking', 'icofont-not-allowed', 
							'icofont-notebook', 'icofont-notepad', 'icofont-notification', 'icofont-numbered', 
							'icofont-opposite', 'icofont-optic', 'icofont-options', 'icofont-package', 'icofont-page', 
							'icofont-paint', 'icofont-paper-plane', 'icofont-paperclip', 'icofont-papers', 'icofont-paw', 
							'icofont-pay', 'icofont-pen', 'icofont-pencil', 'icofont-penguin-linux', 'icofont-pestle', 
							'icofont-phone-circle', 'icofont-phone', 'icofont-picture', 'icofont-pie', 'icofont-pine', 
							'icofont-pixels', 'icofont-play', 'icofont-plugin', 'icofont-plus-circle', 'icofont-plus-square', 
							'icofont-plus', 'icofont-polygonal', 'icofont-power', 'icofont-presentation', 'icofont-price', 
							'icofont-print', 'icofont-puzzle', 'icofont-qr-code', 'icofont-queen', 'icofont-question-circle', 
							'icofont-question-square', 'icofont-question', 'icofont-quote-left', 'icofont-quote-right', 
							'icofont-radio', 'icofont-random', 'icofont-recycle', 'icofont-refresh', 'icofont-repair', 
							'icofont-reply-all', 'icofont-reply', 'icofont-resize', 'icofont-responsive', 'icofont-retweet', 
							'icofont-road', 'icofont-robot', 'icofont-rocket', 'icofont-royal', 'icofont-rss-feed', 
							'icofont-safety', 'icofont-sale-discount', 'icofont-satellite', 'icofont-send-mail', 
							'icofont-server', 'icofont-settings', 'icofont-share-alt', 'icofont-share-boxed', 'icofont-share', 
							'icofont-shield', 'icofont-ship', 'icofont-shopping-cart', 'icofont-sign-in', 'icofont-sign-out', 
							'icofont-signal', 'icofont-site-map', 'icofont-smart-phone', 'icofont-soccer', 'icofont-sort-alt', 
							'icofont-sort', 'icofont-space', 'icofont-spanner', 'icofont-speech-comments', 
							'icofont-speed-meter', 'icofont-spinner-alt-1', 'icofont-spinner-alt-2', 'icofont-spinner-alt-3', 
							'icofont-spinner-alt-4', 'icofont-spinner-alt-5', 'icofont-spinner-alt-6', 'icofont-spinner', 
							'icofont-spreadsheet', 'icofont-square', 'icofont-ssl-security', 'icofont-star-alt-1', 
							'icofont-star-alt-2', 'icofont-star', 'icofont-street-view', 'icofont-sun', 'icofont-support-faq', 
							'icofont-tack-pin', 'icofont-tag', 'icofont-tags', 'icofont-tasks', 'icofont-telephone', 
							'icofont-telescope', 'icofont-terminal', 'icofont-thumbs-down', 'icofont-thumbs-up', 
							'icofont-tick-boxed', 'icofont-tick-mark', 'icofont-ticket', 'icofont-tie', 'icofont-toggle-off', 
							'icofont-toggle-on', 'icofont-tools', 'icofont-transparent', 'icofont-tree', 'icofont-umbrella', 
							'icofont-unlock', 'icofont-unlocked', 'icofont-upload-alt', 'icofont-upload', 'icofont-usb-drive', 
							'icofont-usb', 'icofont-vector-path', 'icofont-verification-check', 'icofont-video-clapper', 
							'icofont-video', 'icofont-volume-down', 'icofont-volume-off', 'icofont-volume-up', 
							'icofont-wall-clock', 'icofont-wall', 'icofont-wallet', 'icofont-warning-alt', 'icofont-warning', 
							'icofont-water-drop', 'icofont-web', 'icofont-wheelchair', 'icofont-wifi-alt', 'icofont-wifi', 
							'icofont-world', 'icofont-zigzag', 'icofont-zipped', 'icofont-social-500px', 
							'icofont-social-baidu-tieba', 'icofont-social-bbm-messenger', 'icofont-social-delicious', 
							'icofont-social-dribbble', 'icofont-social-facebook-messenger', 'icofont-social-flikr', 
							'icofont-social-foursquare', 'icofont-social-google-hangouts', 'icofont-social-kakaotalk', 
							'icofont-social-kik', 'icofont-social-kiwibox', 'icofont-social-linkedin', 'icofont-social-meetme', 
							'icofont-social-odnoklassniki', 'icofont-social-photobucket', 'icofont-social-qq', 
							'icofont-social-renren', 'icofont-social-slack', 'icofont-social-slidshare', 
							'icofont-social-snapchat', 'icofont-social-soundcloud', 'icofont-social-spotify', 
							'icofont-social-stack-exchange', 'icofont-social-stack-overflow', 'icofont-social-tagged', 
							'icofont-social-trello', 'icofont-social-twitch', 'icofont-social-vk', 'icofont-social-weibo', 
							'icofont-social-whatsapp', 'icofont-social-youku', 'icofont-social-youtube-play', 
							'icofont-social-youtube', 'icofont-brand-xiaomi'
						];
					@endphp
					<div class="row">
						@foreach ($icofonts as $icofont)
							<div class="col-md-2 text-center">
								<div class="row">
									<div class="col-12">
										<i class="icofont {{ $icofont }} ico-3x"></i>
									</div>
									<div class="col-12">
										<label>{{ $icofont }}</label>
									</div>
								</div>
							</div>
						@endforeach
					</div>
				</div>
			</div>
		</div>
	</div>
@stop