<?php

namespace Modules\Purchase\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class PurchaseSupplierSpecialtiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $specialities = [
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
            ['name' => ''],
        ];
    }
}
